// Module included in the following assemblies:
//
// assembly-instrumenting-kafka-clients-components-tracers.adoc

[id='proc-enabling-tracing-for-kafka-bridge-{context}']
= Enabling tracing for the Kafka Bridge

Once you have instrumented the Kafka Bridge for distributed tracing (using Interceptors), you need to enable tracing in the Kafka Bridge properties file. This activates the Interceptor classes that you added to the integrated consumers and producers.   

You can then deploy a Kafka Bridge instance that is configured for distributed tracing to the host operating system.

.Procedure

. Enable distributed tracing in the `application.properties` file provided with the {ProductName} Kafka Bridge installation archive.
+
Remove the code comments from the following line:
+
[source,properties,subs="attributes+"]
----
bridge.tracing=jaeger
----

. Run the `kafka_bridge_run.sh` script using the configuration properties as a parameter:
+
[source,shell,%hardbreaks,subs="attributes+"]
----
cd kafka-bridge-0.xy.x.redhat-0000x
./bin/kafka_bridge_run.sh --config-file=config/application.properties
----

.Additional resources

* xref:proc-configuring-kafka-bridge-{context}[]
