// Module included in the following assemblies:
//
// master.adoc

[id='assembly-upgrade-1-1-0-{context}']

= Upgrading an {ProductName} cluster from 1.0.0 to 1.1.0

This section describes how to upgrade {ProductLongName} on Red Hat Enterprise Linux to version 1.1.0, which is based on Apache Kafka 2.1.1, without causing downtime. You must upgrade to {ProductName} 1.1.0 before you can upgrade to Kafka 2.1.1.

Although {ProductName} 1.1.0 and Kafka 2.1.1 are both minor releases, the Kafka protocol has changed since Kafka 2.0.0, with changes to the message format version and inter-broker protocol version (both are version 2.1). Therefore, the upgrade process requires both configuration changes and code changes to client applications (producers and consumers). 

The upgrade process is divided into six separate procedures; Red Hat recommends that you complete them in order.

. Upgrading to {ProductName} 1.1.0
. Upgrading Kafka brokers and client applications to Kafka 2.1.1
.. Updating Kafka brokers to the previous inter-broker protocol and message format versions
.. Updating Kafka brokers to use the new inter-broker protocol version
.. Upgrading client applications to the new Kafka version
.. Updating Kafka brokers to use the new message format version

.Prerequisites
* You have read the https://access.redhat.com/documentation/en-us/[{ProductName} 1.1.0 on Red Hat Enterprise Linux Release Notes].
* You are logged in as the `kafka` user.

.Upgrading to {ProductName} 1.1.0

Before you upgrade your cluster to use the new version, you must download and extract the archived distribution of {ProductName} 1.1.0.
 
To install {ProductName} 1.1.0, complete the following steps.

.Prerequisites
{ProductName} 1.0 is installed on the host machine. For instructions, see xref:proc-installing-amq-streams-{context}[Installing {ProductName}].

.Procedure

. Download the {ProductLongName} 1.1.0 archive from the Software Downloads area of the Red Hat {ReleaseDownload110}.
+
NOTE: If prompted, log in to your Red Hat account. Make sure that 1.1.0 is selected in the Version drop-down list.
+
. On the command line, make sure that the System Security Services Daemon (SSSD) is running.
+
[source,shell,subs=+quotes]
----
sudo sssd
----
+
If SSSD is not running, see http://www.redhat.com[Starting and Stopping SSSD] in the Red Hat Enterprise Linux documentation.

. Change the owner of the archive to the `kafka` user. In this example, the archive was downloaded to the Downloads directory.
+
[source,shell,subs=+quotes]
----
cd Downloads 
sudo chown kafka:kafka amq-streams-1.1.0-bin.zip
----

. Move the archive to the `/opt/kafka` directory that you created during the installation of {ProductName} 1.0.
+
[source,shell,subs=+quotes]
----
sudo mv amq-streams-1.1.0-bin.zip /opt/kafka
----

. Change the current user ID to the `kafka` user and then enter the password. The `kafka` user and password were created during the installation of {ProductName} 1.0.
+
[source,shell,subs=+quotes]
----
su - kafka
Password: ********
----

. As the `kafka` user, extract the contents of the {ProductName} 1.1.0 archive. This example uses the `unzip` command.
+
[source,shell,subs=+quotes]
----
su - kafka
cd /opt/kafka
unzip amq-streams-1.1.0-bin.zip
----

.Upgrading Kafka brokers and client applications to Kafka 2.1.1

Assembly intro - Kafka versions table
 	
.Updating Kafka brokers to the previous inter-broker protocol and message format versions

Manually configure and restart all the Kafka brokers in your cluster to use the previous inter-broker protocol and message format versions (2.0), and then test performance. 

NOTE: To avoid downtime, update and restart the Kafka brokers one-by-one. 

.Prerequisites

* You have upgraded to {ProductName} 1.1.0.

.Procedure

. In a text editor, open the broker properties file (commonly stored in the `/opt/kafka/config/` directory) for the Kafka broker that you want to update.

. Override the default inter-broker protocol and message format versions by adding the following new properties to the file:
+
[source,shell,subs=+quotes]
----
inter.broker.protocol.version=2.0
log.message.format.version=2.0
----
+
This temporarily configures the broker to process data using the previous inter-broker protocol and log message format versions. These are the versions used in Kafka version 2.0.0, on which {ProductName} 1.0 is based.

. Restart the Kafka broker by entering the following command:
+
[source,shell,subs=+quotes]
----
/opt/kafka/bin/kafka-server-start.sh -daemon /opt/kafka/config/server.properties
----
+
NOTE: The broker will start using the 1.1.0 JAR files at this point.

. Repeat steps 1 through 3 for all Kafka brokers in your cluster.

. When all Kafka brokers are updated, test the performance of the cluster.


.Updating Kafka brokers to use the new inter-broker protocol version

If cluster performance testing was successful, manually configure all the Kafka brokers to use the new inter-broker protocol version (2.1). After performing these steps, data is transmitted between the Kafka brokers using inter-broker protocol version 2.1, but messages received are still appended to the message logs in message format version 2.0. 

WARNING: Downgrading to 1.0.0 is not possible after this point.

NOTE: To avoid downtime, update and restart the Kafka brokers one-by-one.

.Prerequisites
* You have upgraded to {ProductName} 1.1.0 and updated Kafka brokers to use the previous inter-broker protocol and message format versions.

.Procedure

. In a text editor, open the broker properties file (commonly stored in the `/opt/kafka/config/` directory) for a Kafka broker.

. Set the `inter.broker.protocol.version` to 2.1.

. Restart the Kafka broker by entering the following command:
+
[source,shell,subs=+quotes]
----
/opt/kafka/bin/kafka-server-start.sh -daemon /opt/kafka/config/server.properties
----

. Repeat steps 1 and 2 for all Kafka brokers in your cluster.

.Upgrading client applications to the new Kafka version

Upgrade consumers and producers to use {ProductName} 1.1.0. Red Hat recommends that you upgrade consumers first, as described in the following procedure.

.Prerequisites

* You have upgraded to {ProductName} 1.1.0, updated Kafka brokers to use the previous inter-broker protocol and message format versions, and updated Kafka brokers to use the new inter-broker protocol version.

.Procedure

. Upgrade all consumers to use version 1.1.0 of the {ProductName} client libraries.

. Optional: If a temporary loss of performance is not acceptable, perform the following steps. Otherwise, go to step three.

.. Set the message format version on a topic-by-topic basis for each producer. This avoids messages received by Kafka brokers from being converted down to message format version 2.0, which is likely to increase CPU usage and affect cluster performance.
+
Set the `message.format.version` configuration option to 2.1 for the topic that you want to update first.
+
[source,shell,subs=+quotes]
----
bin/kafka-configs.sh --zookeeper <ZookeeperAddress> --entity-type topics --entity-name <TopicName> --alter --add-config message.format.version=2.1
----

.. Identify the producer or producers that write data to the topic you modified in step a, and then upgrade them to use message format version 2.1.

.. Repeat steps a and b for all topics in your cluster, and for all producers.

. Optional: If you did not complete step two, upgrade all producers to use message format version 2.1.1.
+
NOTE: Unless you performed step two of the above procedure, messages sent by producers to topics are now converted down to message format version 2.0 before being appended to the message logs. This is likely to cause performance loss. To restore high performance, update all Kafka brokers to use the new message format version as soon as possible -- see XREF Updating Kafka brokers to use the new log message format version.

.Updating Kafka brokers to use the new message format version

When client applications have been upgraded, you can update the Kafka brokers to use the new message format version (2.1). 

NOTE: To avoid downtime, update and restart the Kafka brokers one-by-one.

.Prerequisites
* You have upgraded to {ProductName} 1.1.0, updated Kafka brokers to use the previous inter-broker protocol and message format versions, updated Kafka brokers to use the new inter-broker protocol version, and Upgraded client applications to the new Kafka version.

.Procedure

. In a text editor, open the broker properties file (commonly stored in the `/opt/kafka/config/` directory) for a Kafka broker.

. Set the `log.message.format.version` to 2.1.

. Restart the Kafka broker by entering the following command:
+
[source,shell,subs=+quotes]
----
/opt/kafka/bin/kafka-server-start.sh -daemon /opt/kafka/config/server.properties
----

. Repeat steps 1 through 3 for all Kafka brokers in your cluster.