// This assembly is included in the following assemblies:
//
// master.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='overview-{context}']
= Overview of AMQ Streams

Red Hat AMQ Streams is a massively-scalable, distributed, and high-performance data streaming platform based on the Apache Zookeeper and Apache Kafka projects.
It consists from the following main components:

Zookeeper:: Service for highly reliable distributed coordination.
Kafka Broker:: Messaging broker responsible for delivering records from producing clients to consuming clients.
Kafka Connect:: A toolkit for streaming data between Kafka brokers and other systems using _Connector_ plugins.
Kafka Consumer and Producer APIs:: Java based APIs for producing and consuming messages to / from Kafka brokers.
Kafka Streams API:: API for writing _stream processor_ applications.

Kafka Broker is the central point connecting all these components. 
The broker uses Apache Zookeeper for storing configuration data and for cluster coordination. 
Before running Apache Kafka, an Apache Zookeeper cluster has to be ready.

include::ref-overview-key-features.adoc[leveloffset=+1]

include::ref-overview-supported-configurations.adoc[leveloffset=+1]

include::ref-overview-document-conventions.adoc[leveloffset=+1]