// This assembly is included in the following assemblies:
//
// master.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

[id='monitoring-{context}']
= Monitoring your cluster using JMX

Zookeeper, the Kafka broker, Kafka Connect, and the Kafka clients all expose management information using link:https://www.oracle.com/technetwork/articles/java/javamanagement-140525.html[Java Management Extensions (JMX)]. Most of this management information is in the form of metrics that you can use for monitoring the health of your Kafka cluster.

JMX works at the level of the JVM (Java Virtual Machine).
To obtain management information, external tools can connect to the JVM that is running Zookeeper, the Kafka broker, and so on.
By default, only tools on the same machine and running as the same user as the JVM are able to connect.

include::con-configuring-jmx-options.adoc[leveloffset=+1]

include::con-monitoring-using-jconsole.adoc[leveloffset=+1]

include::con-important-broker-metrics.adoc[leveloffset=+1]

//include::ref-mbeans-zookeeper.adoc[leveloffset=+1]

//include::ref-mbeans-kafka-broker.adoc[leveloffset=+1]

include::ref-mbeans-producer-gen.adoc[leveloffset=+1]

include::ref-mbeans-consumer-gen.adoc[leveloffset=+1]

include::ref-mbeans-kafka-connect-gen.adoc[leveloffset=+1]

include::ref-mbeans-kafka-streams-gen.adoc[leveloffset=+1]
