// This assembly is included in the following assemblies:
//
// master.adoc

[id='assembly-distributed-tracing-{context}']
= Distributed tracing

This chapter outlines the support for distributed tracing in {ProductName} on {ProductPlatformName}, using Jaeger.

To configure distributed tracing, you __instrument__ Kafka clients and components using an OpenTracing client library. This involves adding instrumentation code to your clients and components, which monitors the execution of individual transactions in order to generate trace data.

Before you start instrumenting Kafka clients and components, you must first initialize and configure a Jaeger tracer in the Kafka cluster. This is described in xref:proc-configuring-jaeger-tracer-kafka-clients-{context}[].

NOTE: Distributed tracing is not supported for Kafka brokers.

include::distributed-tracing/con-overview-distributed-tracing.adoc[leveloffset=+1]

.Outline of procedures

To set up distributed tracing for {ProductName}, follow these procedures:

* xref:proc-configuring-jaeger-tracer-kafka-clients-{context}[Initialize a Jaeger tracer for Kafka clients]

* xref:proc-instrumenting-producers-consumers-for-opentracing-{context}[Instrument Kafka Producers and Consumers for tracing]

* xref:proc-instrumenting-kafka-streams-with-tracers-{context}[Instrument Kafka Streams applications for tracing]

* xref:proc-instrumenting-mirror-maker-connect-for-tracing-{context}[Instrument Mirror Maker and Kafka Connect for tracing]

This chapter covers setting up distributed tracing for {ProductName} clients and components only. Setting up distributed tracing for applications and systems beyond {ProductName} is outside the scope of this chapter. To learn more about this subject, see the {OpenTracingDocs} and search for "inject and extract".

.Before you start

Before you set up distributed tracing for {ProductName}, it is helpful to understand:

* The basics of OpenTracing, including key concepts such as traces, spans, and tracers. Refer to the {OpenTracingDocs}.
* The components of the {JaegerArch}. 

.Prerequisites

* The Jaeger backend components are deployed to your host. For deployment instructions, see the https://www.jaegertracing.io/docs/1.14/deployment/[Jaeger deployment documentation^].

include::assembly-setting-up-tracing-kafka-clients.adoc[leveloffset=+1]

include::assembly-instrumenting-kafka-clients-components-tracers.adoc[leveloffset=+1]

//include::assembly-setting-up-tracing-mirror-maker-connect.adoc[leveloffset=+1]