// This assembly is included in the following assemblies:
//
// master.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

= Monitoring

Zookeeper, the Kafka broker, Kafka connect and the Kafka clients all expose management information using [JMX (Java Management Extentions)](https://www.oracle.com/technetwork/articles/java/javamanagement-140525.html). 
Much of this management information takes the form of metrics which can be used for monitoring the health of the cluster.

JMX works at the level of the JVM (Java Virtual Machine).
External tools connect to the JVM running Zookeeper, the Kafka broker, and so on, to obtain the management information.
By default only tools on the same machine and running as the same user as the JVM are able to connect.

include::con-configuring-jmx-options.adoc[leveloffset=+1]

include::con-monitoring-using-jconsole.adoc[leveloffset=+1]

//include::ref-mbeans-zookeeper.adoc[leveloffset=+1]

//include::ref-mbeans-kafka-broker.adoc[leveloffset=+1]

include::ref-mbeans-producer.adoc[leveloffset=+1]

include::ref-mbeans-consumer.adoc[leveloffset=+1]

include::ref-mbeans-kafka-connect.adoc[leveloffset=+1]

//include::ref-mbeans-kafka-streams.adoc[leveloffset=+1]
