// Module included in the following assemblies:
//
// master.adoc

[id='assembly-upgrade-1-1-0-{context}']

= Upgrading an {ProductName} cluster from 1.0.0 to 1.1.0

This chapter describes how to upgrade {ProductName} on Red Hat Enterprise Linux from version 1.0 to version 1.1.0. No cluster downtime is required.

{ProductName} 1.0 and 1.1.0 are based on different versions of Apache Kafka:

[options="header"]
|=======================
|{ProductName} version |Kafka version 
|1.0                   |2.0.0         
|1.1.0                 |2.1.1         
|=======================

Although {ProductName} 1.1.0 and Kafka 2.1.1 are both minor releases, the Kafka protocol has changed since Kafka 2.0.0 was released. In particular, the message format version and inter-broker protocol version are both now at version 2.1. As a result, the upgrade process involves making both configuration changes to existing Kafka brokers and code changes to client applications (consumers and producers). The following table shows the differences between the two Kafka versions:

[options="header"]
|=======================
|Kafka version |Inter-broker protocol version |Log message format version |Zookeeper version
|2.0.0         |2.0                           |2.0                        |3.4.13
|2.1.1         |2.1                           |2.1                        |3.4.13
|=======================

Although Kafka 2.0.0 and 2.1.1 use the same version of Zookeeper, Red Hat recommends that you update your Zookeeper cluster to use the newest Zookeeper binaries before proceeding with the main {ProductName} 1.1.0 upgrade.

Message format version::

When a producer sends a message to a Kafka broker, the message is encoded using a specific format. This is referred to as the message format version. You can configure a Kafka broker to convert messages from newer format versions to a given older format version, before the broker appends the message to the log.

In Kafka, there are two different methods for setting the message format version:

* The `log.message.format.version` property is set on Kafka brokers.

* The `message.format.version` property is set on topics. 

The default value of `message.format.version` for a  topic is defined by the `log.message.format.version` that is set on the Kafka broker. You can manually set the `message.format.version` of a topic by modifying its topic configuration. This chapter refers to the _message format version_ throughout when discussing both Kafka brokers and topics.

Procedure outline::

In summary, upgrading to {ProductName} 1.1.0 is a three-stage process:

. First, you update your Zookeeper cluster to use the newest Zookeeper binaries.

.. xref:proc-updating-zookeeper-binaries-{context}[Updating the Zookeeper binaries]

. Second, you upgrade all Kafka brokers to {ProductName} 1.1.0 and configure them to use the previous protocol versions.
.. xref:proc-upgrading-kafka-brokers-to-amq-streams-1-1-0-{context}[Upgrading Kafka brokers to {ProductName} 1.1.0]

. Third, you upgrade all Kafka brokers and client applications to Kafka 2.1.1. To avoid cluster downtime, this stage involves three related procedures:

.. xref:proc-updating-kafka-brokers-to-new-inter-broker-protocol-version-{context}[Updating Kafka brokers to the new inter-broker protocol version] 

.. Decide on an appropriate strategy for upgrading your client applications based on xref:con-strategies-for-upgrading-clients-{context}[Strategies for upgrading clients].

.. xref:proc-upgrading-clients-to-new-kafka-version-{context}[Upgrading client applications to the new Kafka version] (describes one upgrade strategy in more detail).

.. xref:proc-updating-kafka-brokers-to-new-message-format-version-{context}[Updating Kafka brokers to the new message format version]

To upgrade brokers and clients without downtime, you *must* complete the upgrade procedures in the order shown above.

.Prerequisites

Before you begin these procedures, make sure that:

* {ProductName} 1.0 is installed. For instructions, see xref:proc-installing-amq-streams-{context}[Installing {ProductName}].

* You have read the link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/amq_streams_1.1.0_on_red_hat_enterprise_linux_rhel_release_notes[{ProductName} 1.1.0 on Red Hat Enterprise Linux Release Notes].

include::proc-updating-zookeeper-binaries.adoc[leveloffset=+1]

include::proc-upgrading-kafka-brokers-to-amq-streams-1-1-0.adoc[leveloffset=+1]

include::proc-updating-kafka-brokers-to-new-inter-broker-protocol-version.adoc[leveloffset=+1]

include::con-strategies-for-upgrading-clients.adoc[leveloffset=+1]

include::proc-upgrading-clients-to-new-kafka-version.adoc[leveloffset=+1]

include::proc-updating-kafka-brokers-to-new-message-format-version.adoc[leveloffset=+1]
