// Module included in the following assemblies:
//
// master.adoc

[id='monitoring-{context}']

= Monitoring your cluster using JMX

Zookeeper, the Kafka broker, Kafka Connect, and the Kafka clients all expose management information using link:https://www.oracle.com/technetwork/articles/java/javamanagement-140525.html[Java Management Extensions] (JMX). Most of this management information is in the form of metrics that are useful for monitoring the condition and performance of your Kafka cluster. Like other Java applications, Kafka provides this management information through various managed beans, or MBeans.

JMX works at the level of the JVM (Java Virtual Machine).
To obtain management information, external tools can connect to the JVM that is running Zookeeper, the Kafka broker, and so on.
By default, only tools on the same machine and running as the same user as the JVM are able to connect.

NOTE: The management information available for Zookeeper is not covered here. You can view Zookeeper metrics in JConsole. For more information, see xref:con-monitoring-using-jconsole-str[Monitoring using JConsole]. 

include::con-jmx-configuration-options.adoc[leveloffset=+1]

include::proc-disabling-jmx-agent.adoc[leveloffset=+1]

include::proc-connecting-to-jvm-from-different-machine.adoc[leveloffset=+1]

include::con-monitoring-using-jconsole.adoc[leveloffset=+1]

include::con-important-broker-metrics.adoc[leveloffset=+1]

include::ref-mbeans-producer-gen.adoc[leveloffset=+1]

include::ref-mbeans-consumer-gen.adoc[leveloffset=+1]

include::ref-mbeans-kafka-connect-gen.adoc[leveloffset=+1]

include::ref-mbeans-kafka-streams-gen.adoc[leveloffset=+1]
