// This assembly is included in the following assemblies:
//
// assembly-kafka-bridge-concepts.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

:parent-context-kafka-bridge-overview: {context}

[id='assembly-kafka-bridge-overview-{context}']
= Kafka Bridge overview

:context: kafka-bridge-overview

The {ProductName} Kafka Bridge provides an API for integrating HTTP-based clients with a Kafka cluster running on {ProductPlatformName}. The API enables such clients to produce and consume messages without the requirement to use the native Kafka protocol.

The API has two main resources -- `consumers` and `topics` -- that are exposed and made accessible through endpoints to interact with consumers and producers in your Kafka cluster. The resources relate only to the Kafka Bridge, not the consumers and producers connected directly to Kafka.

You can:

* Send messages to a topic.

* Create and delete consumers.

* Subscribe consumers to topics, so that they start receiving messages from those topics.

* Retrieve a list of the topics to which a consumer is subscribed.

* Unsubscribe consumers from topics.

* Assign partitions to consumers.

* Retrieve messages from topics.

* Commit a list of consumer offsets.

* Seek on a partition, so that a consumer starts receiving messages from the first or last offset position, or a given offset position.

Similar to an {ProductName} installation, you can download the Kafka Bridge files for installation on {ProductPlatformName}. See xref:proc-downloading-kafka-bridge-{context}[].

For more information on configuring the host and port for the `KafkaBridge` resource, see xref:proc-configuring-kafka-bridge-{context}[].

include::con-requests-kafka-bridge.adoc[leveloffset=+1]

include::con-loggers-kafka-bridge.adoc[leveloffset=+1]

include::ref-api-resources-kafka-bridge.adoc[leveloffset=+1]

include::proc-downloading-kafka-bridge.adoc[leveloffset=+1]

include::proc-configuring-kafka-bridge.adoc[leveloffset=+1]

include::proc-installing-kafka-bridge.adoc[leveloffset=+1]

:context: {parent-context-kafka-bridge-overview}
