// Module included in the following assemblies:
//
// master.adoc

[id='assembly-upgrade-1-1-0-{context}']

= Upgrading an {ProductName} cluster from 1.0.0 to 1.1.0

This chapter describes how to upgrade {ProductName} on Red Hat Enterprise Linux to version 1.1.0, which is based on Apache Kafka 2.1.1. No cluster downtime is required. 

Although AMQ Streams 1.1.0 and Kafka 2.1.1 are both minor releases, the Kafka protocol has changed since Kafka 2.0.0 was released (in particular, the message format version and inter-broker protocol version are both now at version 2.1). Therefore, the upgrade process involves configuration changes to your existing Kafka brokers and code changes to client applications (consumers and producers).

Upgrading to {ProductName} 1.1.0 is a two-stage process:

. First, you upgrade your {ProductName} installation to version 1.1.0, and then conduct performance testing.
. Next, you upgrade all Kafka brokers and clients to Kafka 2.1.1. To avoid cluster downtime, this stage involves multiple procedures.

The remainder of this chapter is divided into six separate procedures; Red Hat recommends that you complete them in the order shown.

. xref:proc-upgrading-to-amq-streams-1-1-0-{context}[Upgrading to {ProductName} 1.1.0]
. xref:proc-downgrading-kafka-brokers-to-previous-protocol-versions-{context}[Downgrading Kafka brokers to the previous protocol versions]
. xref:proc-updating-kafka-brokers-to-new-inter-broker-protocol-version-{context}[Updating Kafka brokers to the new inter-broker protocol version]
. xref:proc-upgrading-clients-to-new-kafka-version-{context}[Upgrading client applications to the new Kafka version]
. xref:proc-updating-kafka-brokers-to-new-message-format-version-{context}[Updating Kafka brokers to the new message format version]

.Prerequisites
* You have read the link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/amq_streams_1.1.0_on_red_hat_enterprise_linux_rhel_release_notes[{ProductName} 1.1.0 on Red Hat Enterprise Linux Release Notes].
* You are logged in to Red Hat Enterprise Linux as the `kafka` user that was created during the initial installation of {ProductName}.

include::proc-upgrading-to-amq-streams-1-1-0.adoc[leveloffset=+1]

include::con-kafka-versions-overview.adoc[leveloffset=+1]

include::proc-downgrading-kafka-brokers-to-previous-protocol-versions.adoc[leveloffset=+1]

include::proc-updating-kafka-brokers-to-new-inter-broker-protocol-version.adoc[leveloffset=+1]

include::proc-upgrading-clients-to-new-kafka-version.adoc[leveloffset=+1]

include::proc-updating-kafka-brokers-to-new-message-format-version.adoc[leveloffset=+1]