// Module included in the following assemblies:
//
// assembly-configuring-zookeeper.adoc

[id='con-zookeeper-basic-configuration-{context}']

= Basic configuration

The most important ZooKeeper configuration options are:

`tickTime`:: ZooKeeper’s basic time unit in milliseconds.
It is used for heartbeats and session timeouts.
For example, minimum session timeout will be two ticks.
`dataDir`:: The directory where ZooKeeper stores its transaction log and snapshots of its in-memory database. This should be set to the `/var/lib/zookeeper/` directory created during installation.
`clientPort`:: Port number where clients can connect. Defaults to `2181`.

An example ZooKeeper configuration file `config/zookeeper.properties` is located in the AMQ Streams installation directory.
It is recommended to place the `dataDir` directory on a separate disk device to minimize the latency in ZooKeeper.

ZooKeeper configuration file should be located in `/opt/kafka/config/zookeeper.properties`.
A basic example of the configuration file can be found below.
The configuration file has to be readable by the `kafka` user.

[source,ini]
----
timeTick=2000
dataDir=/var/lib/zookeeper/
clientPort=2181
----
