// Module included in the following assemblies:
//
// assembly-configuring-kafka.adoc

[id='con-kafka-zookeeper-configuration-{context}']

= Zookeeper

Kafka brokers need Zookeeper to store some parts of their configuration as well as to coordinate the cluster (for example to decide which node is a leader for which partition).
Connection details for the Zookeeper cluster are stored in the configuration file.
The field `zookeeper.connect` contains a comma-separated list of hostnames and ports of members of the zookeeper cluster. 

For example:

[source,ini]
----
zookeeper.connect=zoo1.my-domain.com:2181,zoo2.my-domain.com:2181,zoo3.my-domain.com:2181
----

Kafka will use these addresses to connect to the Zookeeper cluster.
With this configuration, all Kafka znodes will be created directly in the root of Zookeeper database.
Therefore, such a Zookeeper cluster could be used only for a single Kafka cluster.
A base (prefix) path can be specified in the Kafka configuration file, so that multiple Kafka clusters can use a single Zookeeper cluster.
It can be added to the end of the Zookeeper connection string:

[source,ini]
----
zookeeper.connect=zoo1.my-domain.com:2181,zoo2.my-domain.com:2181,zoo3.my-domain.com:2181/my-cluster-1
----