// Module included in the following assemblies:
//
// assembly-monitoring.adoc

[id='con-important-broker-metrics-{context}']

= Important Kafka broker metrics

Concept introduction.

.Kafka server metrics

The following table shows a selection of the metrics available for monitoring an individual Kafka broker in your Kafka cluster.

[cols="4*",options="header",stripes="none",separator=¦]
|===

¦Metric
¦MBean
¦Description
¦Expected value

¦Messages in per second
m¦kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec
¦The rate at which individual messages are consumed by the broker.
¦Expected value

¦Bytes in per second
m¦kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec
¦The rate at which data sent from producers is consumed by the broker.
¦Expected value

¦Replication bytes in per second
m¦kafka.server:type=BrokerTopicMetrics,name=ReplicationBytesInPerSec
¦The rate at which data from other brokers is consumed by the broker.
¦Expected value

¦Bytes out per second
m¦kafka.server:type=BrokerTopicMetrics,name=BytesOutPerSec
¦The rate at which data is fetched and read from the broker by consumers.
¦Expected value

¦Replication bytes out per second
m¦kafka.server:type=BrokerTopicMetrics,name=ReplicationBytesOutPerSec
¦The rate at which data is sent from the broker to other brokers.
¦Expected value

¦Under-replicated partitions
m¦kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions
¦The number of partitions that have not been fully replicated in the follower replicas. 
¦Zero

¦Under minimum ISR partition count
m¦kafka.server:type=ReplicaManager,name=UnderMinIsrPartitionCount
¦Description
¦Expected value

¦Partition count
m¦kafka.server:type=ReplicaManager,name=PartitionCount
¦Description
¦Expected value

¦Leader count
m¦kafka.server:type=ReplicaManager,name=LeaderCount
¦Description
¦Expected value

¦ISR shrinks per second
m¦kafka.server:type=ReplicaManager,name=IsrShrinksPerSec
¦Description
¦Expected value

¦ISR expands per second
m¦kafka.server:type=ReplicaManager,name=IsrExpandsPerSec
¦Description
¦Expected value

¦Maximum lag
m¦kafka.server:type=ReplicaFetcherManager,name=MaxLag,clientId=Replica
¦Description
¦Expected value

¦Requests in producer purgatory
m¦kafka.server:type=DelayedOperationPurgatory,name=PurgatorySize,delayedOperation=Produce
¦Description
¦Expected value

¦Requests in fetch purgatory
m¦kafka.server:type=DelayedOperationPurgatory,name=PurgatorySize,delayedOperation=Fetch
¦Description
¦Expected value

¦Request handler average idle percent
m¦kafka.server:type=KafkaRequestHandlerPool,name=RequestHandlerAvgIdlePercent
¦Description
¦Expected value

¦Request
m¦kafka.server:type=Request
¦Description
¦Expected value

¦Zookeeper request latency (milliseconds)
m¦kafka.server:type=ZooKeeperClientMetrics,name=ZooKeeperRequestLatencyMs
¦Description
¦Expected value

¦Zookeeper session state
m¦kafka.server:type=SessionExpireListener,name=SessionState
¦Description
|Expected value

|===

.Kafka network metrics

Intro

[cols="4*",options="header",stripes="none",separator=¦]
|===

¦Metric
¦MBean
¦Description
¦Expected value

¦Requests per second
m¦kafka.network:type=RequestMetrics,name=RequestsPerSec,request={Produce|FetchConsumer|FetchFollower}
¦Description
¦Expected value

¦Request size in bytes
m¦kafka.network:type=RequestMetrics,name=RequestBytes,request=([-.\w]+)
¦Description
¦Expected value

¦Temporary memory size in bytes
m¦kafka.network:type=RequestMetrics,name=TemporaryMemoryBytes,request={Produce|Fetch}
¦Description
¦Expected value

¦Message conversions time
m¦kafka.network:type=RequestMetrics,name=MessageConversionsTimeMs,request={Produce|Fetch}
¦Description
¦Expected value

¦Total request time in milliseconds
m¦kafka.network:type=RequestMetrics,name=TotalTimeMs,request={Produce|FetchConsumer|FetchFollower}
¦Description
¦Expected value

¦Request queue time in milliseconds
m¦kafka.network:type=RequestMetrics,name=RequestQueueTimeMs,request={Produce|FetchConsumer|FetchFollower}
¦Description
¦Expected value

¦Time taken for the leader to process the request
m¦kafka.network:type=RequestMetrics,name=LocalTimeMs,request={Produce|FetchConsumer|FetchFollower}
¦Description
¦Expected value

¦Time the request waits for the follower
m¦kafka.network:type=RequestMetrics,name=RemoteTimeMs,request={Produce|FetchConsumer|FetchFollower}
¦Description
¦Expected value

¦Time the request waits in the response queue
m¦kafka.network:type=RequestMetrics,name=ResponseQueueTimeMs,request={Produce|FetchConsumer|FetchFollower}
¦Description
¦Expected value

¦Response send time
m¦kafka.network:type=RequestMetrics,name=ResponseSendTimeMs,request={Produce|FetchConsumer|FetchFollower}
¦Description
¦Expected value

¦Network processor average idle percent
m¦kafka.network:type=SocketServer,name=NetworkProcessorAvgIdlePercent
¦Description
¦Expected value

|===

.Kafka log metrics

Intro

[cols="4*",options="header",stripes="none",separator=¦]
|===

¦Metric
m¦MBean
¦Description
¦Expected Value

¦Log flush rate and time in milliseconds
m¦kafka.log:type=LogFlushStats,name=LogFlushRateAndTimeMs
¦Description
¦Expected Value

¦Offline log directory count
m¦kafka.log:type=LogManager,name=OfflineLogDirectoryCount
¦Description
¦Expected Value

|===

.Kafka controller metrics

Intro

[cols="4*",options="header",stripes="none",separator=¦]
|===

¦Active controller count
m¦kafka.controller:type=KafkaController,name=ActiveControllerCount
¦Description
¦Expected Value

¦Leader election rate and time in milliseconds
m¦kafka.controller:type=ControllerStats,name=LeaderElectionRateAndTimeMs
¦Description
¦Expected Value

¦Unclean leader elections per second
m¦kafka.controller:type=ControllerStats,name=UncleanLeaderElectionsPerSec
¦Description
¦Expected Value

|===

.Common attributes for Yammer metrics

Explanation

Table of attributes
