// Module included in the following assemblies:
//
// assembly-topics.adoc

[id='con-message-retention-{context}']

= Message retention

The message retention policy defines how long will the messages be stored on the Kafka brokers.
It can be defined based on time, partition size or both.

For example, you can define that the messages should be kept:
* For 7 days
* Until the parition has 1GB of messages. Once the limit is reached, the oldest messages should be removed.
* For 7 days or until the 1GB limit has been reached.
  Whatever limit comes first will be used.

WARNING: Kafka brokers store messages in log segments.
The messages which are passed their retention policy will be deleted only when new log segment is created.
New log segments are created when the previous log segment gets full.
Additionally, users can request new segments to be created periodically.

Additionally, AMQ Streams supports compacting policy.
With compacting policy, the broker will always try to keep the latest message for given key available.
Older messages with the same key will be deleted.