// Module included in the following assemblies:
//
// assembly-monitoring.adoc

[id='con-configuring-jmx-options-{context}']

= Configuring JMX options

JMX is configured using JVM System properties.
The scripts provided with AMQ Streams (`bin/kafka-server-start.sh` and `bin/connect-distributed.sh`, for example) use the `KAFKA_JMX_OPTS` environment variable to set these System properties.
Although Kafka producer, consumer, and streams applications typically start the JVM in their own way, the System properties for configuring JMX are the same.

You can disable the JMX agent within the JVM by setting the system property `com.sun.management.jmxremote=false` before starting the JVM. 
Doing this means that even local JMX tools cannot connect to the JVM.
For example, to disable JMX in a Kafka broker, use the `KAFKA_JMX_OPTS` environment variable to set `com.sun.management.jmxremote=false` before starting the JVM.

[source,shell,subs=+quotes]
----
export KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote=false
bin/kafka-server-start.sh
----

To connect to the JVM from a different machine, configure the port that the JMX agent will listen on by setting the `com.sun.management.jmxremote.port` system property. 

CAUTION: Connecting to the JVM from a different machine is insecure because it allows JMX tools to connect from anywhere, with no authentication.

For example, to configure a Kafka broker to listen for JMX connections on `_<port>_`, use the `KAFKA_JMX_OPTS` environment variable to set `-Dcom.sun.management.jmxremote.port=_<pod>_` before starting the JVM:

[source,shell,subs=+quotes]
----
export KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote=true
  -Dcom.sun.management.jmxremote.port=_<pod>_
  -Dcom.sun.management.jmxremote.authenticate=false
  -Dcom.sun.management.jmxremote.ssl=false"
bin/kafka-server-start.sh
----

IMPORTANT: Red Hat recommends that you configure authentication and SSL to ensure that the remote JMX connection is secure.
For more information about the system properties needed to do this, see the link:https://docs.oracle.com/javase/6/docs/technotes/guides/management/agent.html[JMX documentation].