// Module included in the following assemblies:
//
// assembly-monitoring.adoc

[id='con-important-metrics-{context}']

= Important metrics

Concept introduction.

== Important Kafka broker metrics

|===

|Cell in column 1, row 1 |Cell in column 2, row 1 |Cell in column 3, row 1

.2+|Content in a single cell that spans columns 1, 2, and 3

|Cell in column 1, row 3
|Cell in column 2, row 3
|Cell in column 3, row 3

|===

[cols="3*",options="header"]
|===

|MBean
|MBean attribute
|Description

|MessagesInPerSec
|Count
|value

|
|EventType
|value

|
|FifteenMinuteRate
|value

|
|RateUnit
|value

|
|MeanRate
|value

|
|OneMinuteRate
|value

|
|FiveMinuteRate
|value

|===


hello


[stripes=none]
|===
|MBean              |MBean Attributes       |Description
|MessagesInPerSec   |Count                  |
|cell               |EventType              |
|cell               |FifteenMinuteRate      |
|cell               |RateUnit               |
|cell               |MeanRate               |
|cell               |OneMinuteRate          |
|cell               |FiveMinuteRate         |
|===






Description




//he MBean itself has the orange icon.
//The MBean attributes are directly underneath the MBean.










//All important MBeans//

Message in rate
Byte in rate from clients
Byte in rate from other brokers
Request rate
Error rate
Request size in bytes
Temporary memory size in bytes
Message conversion time
Message conversion rate
Byte out rate to clients
Byte out rate to other brokers
Log flush rate and time
# of under replicated partitions (|ISR| < |all replicas|)
# of under minIsr partitions (|ISR| < min.insync.replicas)
# of offline log directories
Is controller active on broker
Leader election rate
Unclean leader election rate
Partition counts
Leader replica counts
ISR shrink rate
ISR expansion rate
Max lag in messages btw follower and leader replicas
Lag in messages per follower replica
Requests waiting in the producer purgatory
Requests waiting in the fetch purgatory
Request total time
Time the request waits in the request queue
Time the request is processed at the leader
Time the request waits for the follower
Time the request waits in the response queue
Time to send the response
Number of messages the consumer lags behind the producer by. Published by the consumer, not broker.
The average fraction of time the network processors are idle
The average fraction of time the request handler threads are idle
Bandwidth quota metrics per (user, client-id), user or client-id
Request quota metrics per (user, client-id), user or client-id
Requests exempt from throttling
ZooKeeper client request latency
ZooKeeper connection status
