// Module included in the following assemblies:
//
// assembly-configuring-kafka.adoc

[id='con-kafka-zookeeper-configuration-{context}']

= ZooKeeper

Kafka brokers need ZooKeeper to store some parts of their configuration as well as to coordinate the cluster (for example to decide which node is a leader for which partition).
Connection details for the ZooKeeper cluster are stored in the configuration file.
The field `zookeeper.connect` contains a comma-separated list of hostnames and ports of members of the zookeeper cluster. 

For example:

[source,ini]
----
zookeeper.connect=zoo1.my-domain.com:2181,zoo2.my-domain.com:2181,zoo3.my-domain.com:2181
----

Kafka will use these addresses to connect to the ZooKeeper cluster.
With this configuration, all Kafka `znodes` will be created directly in the root of ZooKeeper database.
Therefore, such a ZooKeeper cluster could be used only for a single Kafka cluster.
To configure multiple Kafka clusters to use single ZooKeeper cluster, specify a base (prefix) path at the end of the ZooKeeper connection string in the Kafka configuration file:

[source,ini]
----
zookeeper.connect=zoo1.my-domain.com:2181,zoo2.my-domain.com:2181,zoo3.my-domain.com:2181/my-cluster-1
----