// Module included in the following assemblies:
//
// assembly-topics.adoc

[id='con-message-retention-{context}']

= Message retention

The message retention policy defines how long will the messages be stored on the Kafka brokers.
It can be defined based on time, partition size or both.

For example, you can define that the messages should be kept:
* For 7 days
* Until the parition has 1GB of messages. Once the limit is reached, the oldest messages should be removed.
* For 7 days or until the 1GB limit has been reached.
  Whatever limit comes first will be used.

WARNING: Kafka brokers store messages in log segments.
The messages which are passed their retention policy will be deleted only when new log segment is created.
New log segments are created when the previous log segment gets full.
Additionally, users can request new segments to be created periodically.

Additionally, Kafka brokers supports compacting policy.

With compacting policy, the broker will always keep only the last message for each key.
The older messages with the same key will be removed form the partition.
Because compacting is a periodicaly executed action, it does not happen immediately when the new message with the same key are sent to the partition. 
Instead it might take some time until the older messages are removed.
