// Module included in the following assemblies:
//
// assembly-monitoring.adoc

[id='con-important-broker-metrics-{context}']

= Important Kafka broker metrics

Apache Kafka provides multiple MBeans for monitoring the individual Kafka brokers in your Kafka cluster. The following tables show a selection of important broker-level MBeans organized into server, network, logging, and controller categories.

*Kafka server metrics*

The following table shows a selection of metrics for monitoring a Kafka broker at the server level.

[cols="4*",options="header",stripes="none",separator=¦]
|===

¦Metric
¦MBean
¦Description
¦Expected value

¦Messages in per second
m¦kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec
¦The rate at which individual messages are consumed by the broker.
¦Expected value

¦Bytes in per second
m¦kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec
¦The rate at which data sent from producers is consumed by the broker.
¦Expected value

¦Replication bytes in per second
m¦kafka.server:type=BrokerTopicMetrics,name=ReplicationBytesInPerSec
¦The rate at which data from other brokers is consumed by the broker.
¦Expected value

¦Bytes out per second
m¦kafka.server:type=BrokerTopicMetrics,name=BytesOutPerSec
¦The rate at which data is fetched and read from the broker by consumers.
¦Expected value

¦Replication bytes out per second
m¦kafka.server:type=BrokerTopicMetrics,name=ReplicationBytesOutPerSec
¦The rate at which data is sent from the broker to other brokers.
¦Expected value

¦Under-replicated partitions
m¦kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions
¦The number of partitions that have not been fully replicated in the follower replicas. 
¦Zero

¦Under minimum ISR partition count
m¦kafka.server:type=ReplicaManager,name=UnderMinIsrPartitionCount
¦The number of partitions under the minimum In-Sync Replica Count (ISR).
¦Expected value

¦Partition count
m¦kafka.server:type=ReplicaManager,name=PartitionCount
¦The number of partitions in the broker.
¦A roughly even value.

¦Leader count
m¦kafka.server:type=ReplicaManager,name=LeaderCount
¦The number of leader replicas in the broker.
¦Expected value

¦ISR shrinks per second
m¦kafka.server:type=ReplicaManager,name=IsrShrinksPerSec
¦The rate at which the number of ISRs in the broker decreases
¦0

¦ISR expands per second
m¦kafka.server:type=ReplicaManager,name=IsrExpandsPerSec
¦The rate at which the number of ISRs in the broker increases.
¦0

¦Maximum lag
m¦kafka.server:type=ReplicaFetcherManager,name=MaxLag,clientId=Replica
¦The maximum lag between the time that messages are received by the leader replica and the follower replicas.
¦Expected value

¦Requests in producer purgatory
m¦kafka.server:type=DelayedOperationPurgatory,name=PurgatorySize,delayedOperation=Produce
¦The number of send requests in the producer purgatory.
¦Expected value

¦Requests in fetch purgatory
m¦kafka.server:type=DelayedOperationPurgatory,name=PurgatorySize,delayedOperation=Fetch
¦The number of fetch requests in the fetch purgatory.
¦Expected value

¦Request handler average idle percent
m¦kafka.server:type=KafkaRequestHandlerPool,name=RequestHandlerAvgIdlePercent
¦The average amount of time that the request handler is idle.
¦Expected value

¦Request
m¦kafka.server:type=Request
¦The number of requests that are exempt from throttling.
¦Expected value

¦Zookeeper request latency (milliseconds)
m¦kafka.server:type=ZooKeeperClientMetrics,name=ZooKeeperRequestLatencyMs
¦The latency for ZooKeeper requests from the broker, in milliseconds.
¦Expected value

¦Zookeeper session state
m¦kafka.server:type=SessionExpireListener,name=SessionState
¦The status of the broker's connection to Zookeeper.
|Expected value

|===

*Kafka network metrics*

Intro

[cols="4*",options="header",stripes="none",separator=¦]
|===

¦Metric
¦MBean
¦Description
¦Expected value

¦Requests per second
m¦kafka.network:type=RequestMetrics,name=RequestsPerSec,request={Produce|FetchConsumer|FetchFollower}
¦The total number of requests made for the request type per second.
¦Expected value

¦Request size in bytes
m¦kafka.network:type=RequestMetrics,name=RequestBytes,request=([-.\w]+)
¦The size of requests made for each request type.
¦Expected value

¦Temporary memory size in bytes
m¦kafka.network:type=RequestMetrics,name=TemporaryMemoryBytes,request={Produce|Fetch}
¦The amount of temporary memory used for converting message formats and decompressing messages.
¦Expected value

¦Message conversions time
m¦kafka.network:type=RequestMetrics,name=MessageConversionsTimeMs,request={Produce|Fetch}
¦Time in milliseconds spent on converting message formats.
¦Expected value

¦Total request time in milliseconds
m¦kafka.network:type=RequestMetrics,name=TotalTimeMs,request={Produce|FetchConsumer|FetchFollower}
¦Description ???
¦Expected value

¦Request queue time in milliseconds
m¦kafka.network:type=RequestMetrics,name=RequestQueueTimeMs,request={Produce|FetchConsumer|FetchFollower}
¦The length of time the request spends waiting in the request queue.
¦Expected value

¦Local time in milliseconds
m¦kafka.network:type=RequestMetrics,name=LocalTimeMs,request={Produce|FetchConsumer|FetchFollower}
¦The time taken for the leader to process the request.
¦Expected value

¦Remote time in milliseconds
m¦kafka.network:type=RequestMetrics,name=RemoteTimeMs,request={Produce|FetchConsumer|FetchFollower}
¦The length of time the request waits for the follower.
¦Expected value

¦Response queue time in milliseconds
m¦kafka.network:type=RequestMetrics,name=ResponseQueueTimeMs,request={Produce|FetchConsumer|FetchFollower}
¦The length of time the request waits in the response queue.
¦Expected value

¦Response send time
m¦kafka.network:type=RequestMetrics,name=ResponseSendTimeMs,request={Produce|FetchConsumer|FetchFollower}
¦The time taken to send the response.
¦Expected value

¦Network processor average idle percent
m¦kafka.network:type=SocketServer,name=NetworkProcessorAvgIdlePercent
¦The average percentage of time that the network processors are idle.
¦Expected value

|===

*Kafka log metrics*

Intro

[cols="4*",options="header",stripes="none",separator=¦]
|===

¦Metric
m¦MBean
¦Description
¦Expected Value

¦Log flush rate and time in milliseconds
m¦kafka.log:type=LogFlushStats,name=LogFlushRateAndTimeMs
¦Log flush rate and time
¦Expected Value

¦Offline log directory count
m¦kafka.log:type=LogManager,name=OfflineLogDirectoryCount
¦The number of offline log directories (for example, after a hardware failure).
¦Expected Value

|===

*Kafka controller metrics*

Intro

[cols="4*",options="header",stripes="none",separator=¦]
|===

¦Metric
m¦MBean
¦Description
¦Expected Value

¦Active controller count
m¦kafka.controller:type=KafkaController,name=ActiveControllerCount
¦The number of brokers designated as controllers.
¦If 1, the broker is the controller for the Kafka cluster.

¦Leader election rate and time in milliseconds
m¦kafka.controller:type=ControllerStats,name=LeaderElectionRateAndTimeMs
¦The rate at which new leader replicas are elected.
¦0

|===

.Common attributes for Yammer metrics

Explanation

Table of attributes
