// Module included in the following assemblies:
//
// assembly-kafka-encryption-and-authentication.adoc

[id='proc-kafka-enable-tls-client-authentication-{context}']

= Enabling TLS client authentication

This procedure describes how to enable TLS client authentication in Kafka brokers.

.Prerequisites

* AMQ Streams is xref:proc-installing-amq-streams-{context}[installed] on all hosts which will be used as Kafka brokers.
* TLS encryption is xref:proc-kafka-enable-tls-encryption-{context}[enabled].

.Procedure

. Prepare a JKS truststore containing the public key of the certification authority used to sign the user certificates.

. Edit the `/opt/kafka/config/server.properties` Kafka configuration file on all cluster nodes for the following:
+

* Set the `ssl.truststore.location` option to the path to the JKS truststore with the certification authority of the user certificates.
* Set the `ssl.truststore.password` option to the password you used to protect the truststore.
* Set the `ssl.client.auth` option to `required`.
+
For example:
+
[source]
----
ssl.truststore.location=/path/to/truststore.jks
ssl.truststore.password=123456
ssl.client.auth=required
----

. (Re)start the Kafka brokers

.Additional resources

* For more information about configuring AMQ Streams, see xref:proc-configuring-amq-streams-{context}[].
* For more information about running a Kafka cluster, see xref:proc-running-multinode-kafka-cluster-{context}[].
* For more information about configuring TLS encryption in clients, see:
** xref:producer-configuration-parameters-{context}[]
** xref:consumer-configuration-parameters-{context}[]
