// Module included in the following assemblies:
//
// assembly-upgrading-brokers.adoc

[id='proc-upgrading-clients-to-new-kafka-version-{context}']

= Upgrading client applications to the new Kafka version

This procedure describes one possible approach to upgrading your client applications to the Kafka version used for {ProductName} {ProductVersion}.

The procedure is based on the "per-topic consumers first, with down conversion" approach outlined in xref:con-strategies-for-upgrading-clients-{context}[Strategies for upgrading clients].

Client applications might include producers, consumers, Kafka Connect, and MirrorMaker.

.Prerequisites

* xref:proc-upgrading-zookeeper-binaries-{context}[You have updated the {Zookeeper} binaries.]
* xref:proc-upgrading-kafka-brokers-to-amq-streams-{context}[You have upgraded all Kafka brokers to {ProductName} {ProductVersion}.]
* xref:proc-updating-kafka-brokers-to-new-inter-broker-protocol-version-{context}[You have configured Kafka brokers to use the new inter-broker protocol version.]
* You are logged in to {ProductPlatformName} as the `kafka` user.

.Procedure

For each topic:

. On the command line, set the `message.format.version` configuration option to `{LogMsgVersLower}`.
+
[source,shell,subs="+quotes,attributes"]
----
bin/kafka-configs.sh --zookeeper _<{Zookeeper}Address>_ --entity-type topics --entity-name _<TopicName>_ --alter --add-config message.format.version={LogMsgVersLower}
----

. Upgrade all the consuming and producing applications for the topic.

. Verify that the upgraded applications function correctly.

. Change the topic's `message.format.version` configuration option to `{LogMsgVersHigher}`.
+
[source,shell,subs="+quotes,attributes"]
----
bin/kafka-configs.sh --zookeeper _<{Zookeeper}Address>_ --entity-type topics --entity-name _<TopicName>_ --alter --add-config message.format.version={LogMsgVersHigher}
----

.Additional resources

* xref:con-strategies-for-upgrading-clients-{context}[Strategies for upgrading clients]
