// Module included in the following assemblies:
//
// assembly-upgrade-1-1-0.adoc
[id='proc-updating-kafka-brokers-to-previous-protocol-versions-{context}']

= Updating Kafka brokers to the previous protocol versions

Manually configure and restart all the Kafka brokers in your cluster to use the previous inter-broker protocol and message format versions (2.0). 

NOTE: To avoid cluster downtime, update and restart the Kafka brokers one-by-one. 

.Prerequisites

* You have updated the Zookeeper binaries
* You are logged in to Red Hat Enterprise Linux as the `kafka` user.

.Procedure

. In a text editor, open the broker properties file for the Kafka broker you want to update first. These files are commonly stored in the `/opt/kafka/config/` directory.

. Temporarily override the default inter-broker protocol and message format versions for Kafka 2.1.1 by adding the following new properties to the file:
+
[source,shell,subs=+quotes]
----
inter.broker.protocol.version=2.0
log.message.format.version=2.0
----
+
This configures the Kafka broker to process data using the previous inter-broker protocol and message format versions.

. On the command line, restart the Kafka broker:
+
[source,shell,subs=+quotes]
----
/opt/kafka/bin/kafka-server-start.sh -daemon /opt/kafka/config/server.properties
----
+
NOTE: The broker will start using the version 1.1.0 JAR files.

. Repeat steps 1 through 3 for all Kafka brokers in your cluster.