// Module included in the following assemblies:
//
// assembly-upgrade-1-1-0.adoc

[id='proc-upgrading-clients-to-new-kafka-version-{context}']

= Upgrading client applications to the new Kafka version

This procedure describes one possible approach to upgrading your client applications to Kafka 2.1.1, the version used in {ProductName} 1.1.0. It is based on the "Per-topic consumers first, with down conversion" approach outlined in xref:con-strategies-for-upgrading-clients-{context}[Strategies for upgrading clients]. Client applications might include producers, consumers, Kafka Connect, and MirrorMaker.

.Prerequisites

* xref:proc-updating-zookeeper-binaries-{context}[You have updated the Zookeeper binaries.]
* xref:proc-upgrading-kafka-brokers-to-amq-streams-1-1-0-{context}[You have upgraded all Kafka brokers to {ProductName} 1.1.0.]
* xref:proc-updating-kafka-brokers-to-new-inter-broker-protocol-version-{context}[You have configured Kafka brokers to use the new inter-broker protocol version.]
* You are logged in to Red Hat Enterprise Linux as the `kafka` user.

.Procedure

For each topic:

. On the command line, set the `message.format.version` configuration option to `2.0`.
+
[source,shell,subs=+quotes]
----
bin/kafka-configs.sh --zookeeper _<ZookeeperAddress>_ --entity-type topics --entity-name <TopicName> --alter --add-config message.format.version=2.0
----

. Upgrade all the consuming and producing applications for the topic.

. Verify that the upgraded applications function correctly.

. Change the topic's `message.format.version` configuration option to `2.1`.
+
[source,shell,subs=+quotes]
----
bin/kafka-configs.sh --zookeeper _<ZookeeperAddress>_ --entity-type topics --entity-name <TopicName> --alter --add-config message.format.version=2.1
----

.Additional resources

* xref:con-strategies-for-upgrading-clients-{context}[Strategies for upgrading clients]
