// Module included in the following assemblies:
//
// assembly-kafka-authorization.adoc

[id='proc-kafka-authorization-list-rules-{context}']

= Listing ACL rules

This procedure will show you how to list existing ACL rules when using the `SimpleAclAuthorizer` plugin in Kafka brokers.

.Prerequisites

* AMQ Streams cluster is installed and running
* Authorization is xref:proc-kafka-enable-authorization-{context}[enabled] in Kafka brokers.

.Removing ACL rules

. `kafka-acls.sh` utility can be used to manage ACL rules.
To list existing rules, call it with option `--list`.
Following examples shows list of existing ACL rules.
+
[source]
----
$ bin/kafka-acls.sh --authorizer-properties zookeeper.connect=zoo1.my-domain.com:2181 --list --topic myTopic
Current ACLs for resource `Topic:myTopic`:
        User:user1 has Allow permission for operations: Read from hosts: *
        User:user2 has Allow permission for operations: Read from hosts: *
        User:user2 has Deny permission for operations: Read from hosts: 127.0.0.1
        User:user1 has Allow permission for operations: Describe from hosts: *
        User:user2 has Allow permission for operations: Describe from hosts: *
        User:user2 has Deny permission for operations: Describe from hosts: 127.0.0.1
----

.Additional resources

* For a list of all `kafka-acls.sh` options, see xref:con-kafka-authorization-simple-{context}[].
* For more information about enabling authorization, see xref:proc-kafka-enable-authorization-{context}[].