// Module included in the following assemblies:
//
// assembly-getting-started.adoc

[id='proc-downloading-and-installing-amq-streams-{context}']

= Downloading and Installing AMQ Streams

.Prerequisites

* AMQ Streams is available for following platforms:
+
Red Hat Enterprise Linux 7 / x86_64
* It requires following components to be installed:
+
Java Runtime Environment 8 (OpenJDK 8, OracleJDK 8, IBM JDK 8)

.Procedure

. Add new `kafka` user and group:
+
[source,shell,subs=+quotes]
----
sudo groupadd kafka
sudo useradd -g kafka kafka
sudo passwd kafka
----

. Create directory `/opt/kafka`:
+
[source,shell,subs=+quotes]
----
sudo mkdir /opt/kafka
----

. Download AMQ Streams {ReleaseDownload} and unpack the archive into `/opt/kafka` directory
+
[source,shell,subs=+quotes]
----
sudo tar xvfz kafka_y.y-x.x.x.tar.gz -C /opt/kafka --strip-components=1
----

. Change the ownership of the `/opt/kafka` directory to the `kafka` user:
+
[source,shell,subs=+quotes]
----
sudo chown -R kafka:kafka /opt/kafka
----

. Create directory `/var/lib/zookeeper` for storing Zookeeper data and set its ownership to the `kafka` user:
+
[source,shell,subs=+quotes]
----
sudo mkdir /var/lib/zookeeper
sudo chown -R kafka:kafka /var/lib/zookeeper
----

. Create directory `/var/lib/kafka` for storing Kafka data and set its ownership to the `kafka` user:
+
[source,shell,subs=+quotes]
----
sudo mkdir /var/lib/kafka
sudo chown -R kafka:kafka /var/lib/kafka
----