// Module included in the following assemblies:
//
// assembly-upgrading-brokers.adoc

[id='proc-upgrading-kafka-brokers-to-amq-streams-{context}']

= Upgrading Kafka brokers

This procedure describes how to upgrade Kafka brokers on a host machine.

.Prerequisites

* You are logged in to Red Hat Enterprise Linux as the `kafka` user.

.Procedure

For each Kafka broker in your {ProductName} cluster and one at a time:

. Download the {ProductName} archive from the {ReleaseDownload}.
+
NOTE: If prompted, log in to your Red Hat account.

. On the command line, create a temporary directory and extract the contents of the `amq-streams-x.y.z-bin.zip` file.
+
[source,shell,subs=+quotes]
----
mkdir /tmp/kafka-x-y-z
unzip amq-streams-x.y.z-bin.zip -d /tmp/kafka-x-y-z
----

. Delete the `libs`, `bin`, and `docs` directories from your existing installation:
+
[source,shell,subs=+quotes]
----
rm -rf /opt/kafka/libs /opt/kafka/bin /opt/kafka/docs
----

. Copy the `libs`, `bin`, and `docs` directories from the temporary directory:
+
[source,shell,subs=+quotes]
----
cp -r /tmp/kafka-x-y-z/kafka_y.y-x.x.x/libs /opt/kafka/
cp -r /tmp/kafka-x-y-z/kafka_y.y-x.x.x/bin /opt/kafka/
cp -r /tmp/kafka-x-y-z/kafka_y.y-x.x.x/docs /opt/kafka/
----

. Delete the temporary directory.
+
[source,shell,subs=+quotes]
----
rm -r /tmp/kafka-x-y-z
----

. In a text editor, open the broker properties file, commonly stored in the `/opt/kafka/config/` directory.

. Temporarily override the default inter-broker protocol and message format versions for Kafka {DefaultKafkaVersion} by adding or updating the following properties in the file:
+
[source,shell,subs="+quotes,attributes"]
----
inter.broker.protocol.version={LogMsgVersLower}
log.message.format.version={LogMsgVersLower}
----
+
This configures the Kafka broker to process data using the previous inter-broker protocol (`{LogMsgVersLower}`) and message format versions.

. On the command line, stop the Kafka broker that you modified:
+
[source,shell,subs=+quotes]
----
/opt/kafka/bin/kafka-server-stop.sh
jcmd | grep kafka
----

. Restart the Kafka broker that you modified:
+
[source,shell,subs=+quotes]
----
/opt/kafka/bin/kafka-server-start.sh -daemon /opt/kafka/config/server.properties
----
+
NOTE: The Kafka broker will start using the binaries for the latest Kafka version.

. Verify that the restarted Kafka broker has caught up with the partition replicas it is following. Use the `kafka-topics.sh` tool to ensure that all replicas contained in the broker are back in sync. For instructions, see xref:proc-describing-a-topic-{context}[Listing and describing topics].
