// Module included in the following assemblies:
//
// assembly-kafka-connect-standalone.adoc

[id='proc-running-kafka-connect-standalone-{context}']

= Running Kafka Connect in standalone mode

This procedure describes how to configure and run Kafka Connect in standalone mode.

.Prerequisites

* An installed and running {ProductName}} cluster.

.Procedure

. Edit the ``/opt/kafka/config/connect-standalone.properties`` Kafka Connect configuration file and set ``bootstrap.server`` to point to your Kafka brokers. For example:
+
[source,ini]
bootstrap.servers=kafka0.my-domain.com:9092,kafka1.my-domain.com:9092,kafka2.my-domain.com:9092

. Start Kafka Connect with the configuration file and specify one or more connector configurations.
+
[source,shell]
----
su - kafka
/opt/kafka/bin/connect-standalone.sh /opt/kafka/config/connect-standalone.properties connector1.properties 
[connector2.properties ...]
----

. Verify that Kafka Connect is running.
+
[source,shell]
   jcmd | grep ConnectStandalone

.Additional resources

* For more information on installing AMQ Streams, see xref:proc-installing-amq-streams-{context}[].

* For more information on configuring AMQ Streams, see xref:proc-configuring-amq-streams-{context}[].

* For a complete list of supported Kafka Connect configuration options, see xref:kafka-connect-configuration-parameters-{context}[].
