// Module included in the following assemblies:
//
// assembly-configuring-zookeeper.adoc

[id='proc-running-multinode-zookeeper-cluster-{context}']

= Running multi-node Zookeeper cluster

This procedure will show you how to configure and run Zookeeper as a multi-node cluster.

.Prerequisites

* AMQ Streams is installed on all hosts which will be used as Zookeeper cluster nodes.

.Running the cluster

. Create the `myid` file in `/var/lib/zookeeper/`.
Enter ID `1` for the first Zookeeper node, `2` for the second Zookeeper, node and so on.
+
----
su - kafka
echo "_<NodeID>_" > /var/lib/zookeeper/myid
----
+
For example:
+
----
su - kafka
echo "1" > /var/lib/zookeeper/myid
----

. Edit the Zookeeper configuration file `/opt/kafka/config/zookeeper.properties`.
Set the option `dataDir` to `/var/lib/zookeeper/`.
Configure the options `initLimit` and `syncLimit`.
Add a list of all Zookeeper nodes.
The list should include also the current node.
+
.Example configuation for a node of Zookeeper cluster with 5 members
[source,ini]
----
timeTick=2000
dataDir=/var/lib/zookeeper/
clientPort=2181
initLimit=5
syncLimit=2

server.1=172.17.0.1:2888:3888
server.2=172.17.0.2:2888:3888
server.3=172.17.0.3:2888:3888
server.4=172.17.0.4:2888:3888
server.5=172.17.0.5:2888:3888
----

. Start Apache Zookeeper with the default configuration file.
+
[source,shell,subs=+quotes]
----
su - kafka
/opt/kafka/bin/zookeeper-server-start.sh -daemon /opt/kafka/config/zookeeper.properties
----

. Make sure that Apache Zookeeper is running.
+
[source,shell,subs=+quotes]
----
jcmd | grep zookeeper
----

. Repeat this procedure on all the nodes of the cluster.

. Once all nodes of the clusters are up and running, you can verify that all nodes are members of the cluster.
You can do it by sending a `stat` command to each of the nodes using `ncat` utility.
+
.Use ncat stat to check the node status
[source,shell,subs=+quotes]
----
echo stat | ncat localhost 2181
----
+
In the output you should see information that the node is either `leader` or `follower`.
+
.Example output from the `ncat` command
[source,subs=+quotes]
----
Zookeeper version: 3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03, built on 06/29/2018 00:39 GMT
Clients:
 /0:0:0:0:0:0:0:1:59726[0](queued=0,recved=1,sent=0)

Latency min/avg/max: 0/0/0
Received: 2
Sent: 1
Connections: 1
Outstanding: 0
Zxid: 0x200000000
**Mode: follower**
Node count: 4
----

.Additional resources

* For more information about installing AMQ Streams, see xref:proc-installing-amq-streams-{context}[].
* For more information about configuring AMQ Streams, see xref:proc-configuring-amq-streams-{context}[].