// Module included in the following assemblies:
//
// assembly-kafka-authorization.adoc

[id='proc-kafka-authorization-remove-rules-{context}']

= Removing ACL rules

This procedure describes how to remove ACL rules when using the `SimpleAclAuthorizer` plugin in Kafka brokers.

Rules are removed using the `kafka-acls.sh` utility.

.Prerequisites

* xref:proc-installing-amq-streams-{context}[AMQ Streams is installed] on all hosts used as Kafka brokers.
* Authorization is xref:proc-kafka-enable-authorization-{context}[enabled] in Kafka brokers.
* ACLs have been xref:proc-kafka-authorization-add-rules-{context}[added].

.Procedure

* Run `kafka-acls.sh` with the `--remove` option.
+
Examples:
+
* Remove the ACL allowing Allow `user1` and `user2` access to read from `myTopic` using the `MyConsumerGroup` consumer group.
+
[source,shell]
----
bin/kafka-acls.sh --authorizer-properties zookeeper.connect=zoo1.my-domain.com:2181 --remove --operation Read --topic myTopic --allow-principal User:user1 --allow-principal User:user2

bin/kafka-acls.sh --authorizer-properties zookeeper.connect=zoo1.my-domain.com:2181 --remove --operation Describe --topic myTopic --allow-principal User:user1 --allow-principal User:user2

bin/kafka-acls.sh --authorizer-properties zookeeper.connect=zoo1.my-domain.com:2181 --remove --operation Read --operation Describe --group MyConsumerGroup --allow-principal User:user1 --allow-principal User:user2
----
+
* Remove the ACL adding `user1` as the consumer of `myTopic` with `MyConsumerGroup`.
+
[source,shell]
----
bin/kafka-acls.sh --authorizer-properties zookeeper.connect=zoo1.my-domain.com:2181 --remove --consumer --topic myTopic --group MyConsumerGroup --allow-principal User:user1
----
+
* Remove the ACL denying `user1` access to read `myTopic` from IP address host `127.0.0.1`.
+
[source,shell]
----
bin/kafka-acls.sh --authorizer-properties zookeeper.connect=zoo1.my-domain.com:2181 --remove --operation Describe --operation Read --topic myTopic --group MyConsumerGroup --deny-principal User:user1 --deny-host 127.0.0.1
----

.Additional resources

* For a list of all `kafka-acls.sh` options, see xref:con-kafka-authorization-simple-{context}[].
* For more information about enabling authorization, see xref:proc-kafka-enable-authorization-{context}[].
