// Module included in the following assemblies:
//
// assembly-kafka-connect-standalone.adoc

[id='proc-running-kafka-connect-standalone-{context}']

= Running standalone Kafka Connect

This procedure will show you how to configure and run Kafka Connect in standalone mode.

.Prerequisites

* AMQ Streams cluster is installed and running

.Running the cluster

. Edit the `/opt/kafka/config/connect-standalone.properties` Kafka Connect configuration file and set the `bootstrap.server` option to point to your Kafka brokers.
For example:
+
[source,ini]
----
bootstrap.servers=kafka0.my-domain.com:9092,kafka1.my-domain.com:9092,kafka2.my-domain.com:9092
----

. Start the Kafka Connect with the configuration file and with one or more connector configurations.
+
[source,shell,subs=+quotes]
----
su - kafka
/opt/kafka/bin/connect-standalone.sh /opt/kafka/config/connect-standalone.properties connector1.properties [connector2.properties ...]
----

. Verify that Kafka Connect is running.
+
[source,shell,subs=+quotes]
----
jcmd | grep ConnectStandalone
----

.Additional resources

* For more information about installing AMQ Streams, see xref:proc-installing-amq-streams-{context}[].
* For more information about configuring AMQ Streams, see xref:proc-configuring-amq-streams-{context}[].
* For a complete list of supported Kafka Connect configuration options, see xref:kafka-connect-configuration-parameters-{context}[].