// Module included in the following assemblies:
//
// assembly-upgrade-1-1-0.adoc

[id='proc-upgrading-clients-to-new-kafka-version-{context}']

= Upgrading client applications to the new Kafka version

Upgrade your consumers and producers to use {ProductName} 1.1.0. Red Hat recommends that you upgrade consumers first, as described in the following procedure.

Because the message format version of the Kafka brokers is still set to version 2.0, upgrading client applications can cause a reduction in the performance of the cluster. This is because any version 2.1 messages received by the brokers are converted down to message format version 2.0 before they are appended to the message logs. This process increases CPU usage. 

To mitigate any reduction in performance, consider upgrading clients on a topic-by-topic basis, starting with topics that have a low throughput, so that the process of converting down to message format version 2.0 only happens on a few topics at a time. You can then upgrade the producers of those topics.

To restore normal performance, you must update all Kafka brokers to use message format version 2.1 as soon as possible after upgrading client applications. For details, see xref:proc-updating-kafka-brokers-to-new-message-format-version-{context}[Updating Kafka brokers to the new message format version].

.Prerequisites

* You have updated the Zookeeper binaries.
* You have updated all Kafka brokers to use the previous inter-broker protocol and message format versions (2.0).
* You have upgraded all Kafka brokers to {ProductName} 1.1.0.
* You have updated Kafka brokers to use the new inter-broker protocol version (2.1).
* You are logged in to Red Hat Enterprise Linux as the `kafka` user.

.Procedure

. Upgrade all consumers to use version 2.1.1 of the Kafka client libraries.

. Optional: To mitigate any reduction in the performance of the cluster, perform the following steps. Otherwise, go to step three.

.. Set the message format version on a topic-by-topic basis for each producer.
+
On the command line, set the `message.format.version` configuration option to `2.1` for the topic that you want to update first.
+
[source,shell,subs=+quotes]
----
bin/kafka-configs.sh --zookeeper _<ZookeeperAddress>_ --entity-type topics --entity-name <TopicName> --alter --add-config message.format.version=2.1
----

.. Identify the producer or producers that write data to the topic you modified in step 2a, and then upgrade them to use message format version 2.1.

.. Repeat steps 2a and 2b for all topics in your cluster, and for all producers.

. As long as all consumers are now updated to use version 2.1.1 of the Kafka client libraries, you can update the producers to use message format version 2.1.
+
NOTE: To restore normal performance, update all Kafka brokers to use message format version 2.0 as soon as possible. For details, see xref:proc-updating-kafka-brokers-to-new-message-format-version-{context}[Updating Kafka brokers to the new message format version].