// Module included in the following assemblies:
//
// assembly-kafka-zookeeper-authorization.adoc

[id='proc-kafka-migrating-zookeeper-acls-{context}']

= Enabling Zookeeper ACLs in existing Kafka cluster

The tool `zookeeper-security-migration.sh` can to be used to set Zookeeper ACLs on all existing `znodes`.
`zookeeper-security-migration.sh` is part of AMQ Streams and can be found in the `bin` directory.

.Prerequisites

* Kafka cluster is xref:proc-running-multinode-kafka-cluster-{context}[configured and running].

.Enabling the Zookeeper ACLs

. Edit the `/opt/kafka/config/server.properties` Kafka configuration file on all cluster nodes for the following:
+
* Set the `zookeeper.set.acl` field to `true`.
+
[source]
----
zookeeper.set.acl=true
----

. Restart all Kafka brokers one by one

. Set the ACLs on all existing Zookeeper `znodes` using the `zookeeper-security-migration.sh` tool.
+
To set the ACLs, run the following command:
+
[source]
----
su - kafka
cd /opt/kafka
KAFKA_OPTS="-Djava.security.auth.login.config=./config/jaas.conf"; ./bin/zookeeper-security-migration.sh --zookeeper.acl=secure --zookeeper.connect=_<ZookeeperURL>_
exit
----
+
For example:
+
[source]
----
su - kafka
cd /opt/kafka
KAFKA_OPTS="-Djava.security.auth.login.config=./config/jaas.conf"; ./bin/zookeeper-security-migration.sh --zookeeper.acl=secure --zookeeper.connect=zoo1.my-domain.com:2181
exit
----
