// Module included in the following assemblies:
//
// assembly-upgrade-1-1-0.adoc

[id='proc-updating-kafka-brokers-to-new-inter-broker-protocol-version-{context}']

= Configuring Kafka brokers to use the new inter-broker protocol version

Manually configure and restart all Kafka brokers to use the new inter-broker protocol version (2.1). After performing these steps, data is transmitted between the Kafka brokers using inter-broker protocol version 2.1. Messages received are still appended to the message logs in message format version 2.0.

WARNING: Downgrading to {ProductName} 1.0.0 is not possible after completing this procedure.

.Prerequisites

* xref:proc-updating-zookeeper-binaries-{context}[You have updated the Zookeeper binaries.]
* xref:proc-upgrading-kafka-brokers-to-amq-streams-1-1-0-{context}[You have upgraded all Kafka brokers to {ProductName} 1.1.0.]
* You are logged in to Red Hat Enterprise Linux as the `kafka` user.

.Procedure

For each Kafka broker in your {ProductName} cluster and one at a time:

. In a text editor, open the broker properties file for the Kafka broker you want to update. Broker properties files are commonly stored in the `/opt/kafka/config/` directory.

. Set the `inter.broker.protocol.version` to `2.1`.
+
[source,shell,subs=+quotes]
----
inter.broker.protocol.version=2.1
----

. On the command line, stop the Kafka broker that you most recently modified and restarted as part of this procedure. If you are modifying the first Kafka broker in this procedure, go to step four.
+
[source,shell,subs=+quotes]
----
/opt/kafka/bin/kafka-server-stop.sh
jcmd | grep kafka
----

. Restart the Kafka broker whose configuration you modified in step two:
+
[source,shell,subs=+quotes]
----
/opt/kafka/bin/kafka-server-start.sh -daemon /opt/kafka/config/server.properties
----

. Verify that the restarted Kafka broker has caught up with the partition replicas it is following. Use the `kafka-topics.sh` tool to ensure that all replicas contained in the broker are back in sync. For instructions, see xref:proc-describing-a-topic-{context}[Listing and describing topics].
