// Module included in the following assemblies:
//
// assembly-getting-started.adoc

[id='proc-installing-amq-streams-{context}']

= Installing AMQ Streams

Follow this procedure to install the latest version of {ProductName} on Red Hat Enterprise Linux. For instructions on upgrading an existing cluster to {ProductName} version 1.1.0, see xref:assembly-upgrade-1-1-0-{context}[Upgrading an {ProductName} cluster from 1.0.0 to 1.1.0].

.Prerequisites

* Download the xref:proc-downloading-amq-streams-{context}[installation archive].
* Review the xref:overview-supported-configurations-{context}[]

.Procedure

. Add new `kafka` user and group.
+
[source,shell,subs=+quotes]
----
sudo groupadd kafka
sudo useradd -g kafka kafka
sudo passwd kafka
----

. Create directory `/opt/kafka`.
+
[source,shell,subs=+quotes]
----
sudo mkdir /opt/kafka
----

. Create a temporary directory and extract the contents of the AMQ Streams ZIP file.
+
[source,shell,subs=+quotes]
----
mkdir /tmp/kafka
unzip _amq-streams_y.y-x.x.x.zip_ -d /tmp/kafka
----

. Move the extracted contents into `/opt/kafka` directory and delete the temporary directory.
+
[source,shell,subs=+quotes]
----
sudo mv /tmp/kafka/_kafka_y.y-x.x.x_/* /opt/kafka/
rm -r /tmp/kafka
----

. Change the ownership of the `/opt/kafka` directory to the `kafka` user.
+
[source,shell,subs=+quotes]
----
sudo chown -R kafka:kafka /opt/kafka
----

. Create directory `/var/lib/zookeeper` for storing Zookeeper data and set its ownership to the `kafka` user.
+
[source,shell,subs=+quotes]
----
sudo mkdir /var/lib/zookeeper
sudo chown -R kafka:kafka /var/lib/zookeeper
----

. Create directory `/var/lib/kafka` for storing Kafka data and set its ownership to the `kafka` user.
+
[source,shell,subs=+quotes]
----
sudo mkdir /var/lib/kafka
sudo chown -R kafka:kafka /var/lib/kafka
----
