// Module included in the following assemblies:
//
// assembly-kafka-encryption-and-authentication.adoc

[id='proc-kafka-enable-scram-authentication-{context}']

= Enabling SASL SCRAM authentication

This procedure describes how to enable SASL SCRAM authentication in Kafka brokers.

.Prerequisites

* AMQ Streams is xref:proc-installing-amq-streams-{context}[installed] on all hosts which will be used as Kafka brokers.

.Procedure

. Edit or create the `/opt/kafka/config/jaas.conf` JAAS configuration file.
Enable the `ScramLoginModule` for the `KafkaServer` context.
Make sure this file is the same on all Kafka brokers.
+
For example:
+
[source]
----
KafkaServer {
    org.apache.kafka.common.security.scram.ScramLoginModule required;
};
----

. Edit the `/opt/kafka/config/server.properties` Kafka configuration file on all cluster nodes for the following:
+
* Change the `listener.security.protocol.map` field to specify the `SASL_PLAINTEXT` or `SASL_SSL` protocol for the listener where you want to use SASL SCRAM authentication.
* Set the `sasl.enabled.mechanisms` option to `SCRAM-SHA-256` or `SCRAM-SHA-512`.
+
For example:
+
[source]
----
listeners=INSECURE://:9092,AUTHENTICATED://:9093,REPLICATION://:9094
listener.security.protocol.map=INSECURE:PLAINTEXT,AUTHENTICATED:SASL_PLAINTEXT,REPLICATION:PLAINTEXT
sasl.enabled.mechanisms=SCRAM-SHA-512
----

. (Re)start the Kafka brokers using the KAFKA_OPTS environment variable to pass the JAAS configuration to Kafka brokers.
+
[source]
----
su - kafka
export KAFKA_OPTS="-Djava.security.auth.login.config=/opt/kafka/config/jaas.conf"; /opt/kafka/bin/kafka-server-start.sh -daemon /opt/kafka/config/server.properties
----

.Additional resources

* For more information about configuring AMQ Streams, see xref:proc-configuring-amq-streams-{context}[].
* For more information about running a Kafka cluster, see xref:proc-running-multinode-kafka-cluster-{context}[].
* For more information about adding SASL SCRAM users, see xref:proc-kafka-adding-scram-users-{context}[].
* For more information about deleting SASL SCRAM users, see xref:proc-kafka-deleting-scram-users-{context}[].
* For more information about configuring SASL SCRAM authentication in clients, see:
** xref:producer-configuration-parameters-{context}[]
** xref:consumer-configuration-parameters-{context}[]
