// Module included in the following assemblies:
//
// assembly-kafka-encryption-and-authentication.adoc

[id='proc-kafka-adding-scram-users-{context}']

= Adding SASL SCRAM users

This procedure describes how to add new users for authentication using SASL SCRAM.

.Prerequisites

* AMQ Streams is xref:proc-installing-amq-streams-{context}[installed] on all hosts which will be used as Kafka brokers.
* SASL SCRAM authentication is xref:proc-kafka-enable-scram-authentication-{context}[enabled].

.Procedure

* Use the `kafka-configs.sh` tool to add new SASL SCRAM users.
+
[source,shell,subs="+quotes,attributes"]
bin/kafka-configs.sh --zookeeper _<ZooKeeperAddress>_ --alter --add-config 'SCRAM-SHA-512=[password=_<Password>_]' --entity-type users --entity-name _<Username>_
+
For example:
+
[source,subs=+quotes]
bin/kafka-configs.sh --zookeeper zoo1.my-domain.com:2181 --alter --add-config 'SCRAM-SHA-512=[password=123456]' --entity-type users --entity-name user1

.Additional resources

* For more information about configuring SASL SCRAM authentication in clients, see:
** xref:producer-configuration-parameters-{context}[]
** xref:consumer-configuration-parameters-{context}[]
