// Module included in the following assemblies:
//
// assembly-topics.adoc

[id='proc-deleting-a-topic-{context}']

= Deleting a topic

The `kafka-topics.sh` tool can be used to manage topics.
`kafka-topics.sh` is part of the AMQ Streams distribution and can be found in the `bin` directory.

.Prerequisites

* AMQ Streams cluster is installed and running
* Topic `myTopic` exists

.Deleting a topic

. Delete a topic using the `kafka-topics.sh` utility.
Specify the Zookeeper URL in the `--zookeeper` options.
Use `--delete` option to specify that an existing topic should be deleted.
Topic name has to be specified in the `--topic` option.
+
[source,shell,subs=+quotes]
bin/kafka-topics.sh --zookeeper  _<ZookeeperAddress>_ --delete --topic _<TopicName>_
+
.Example of command to create a topic named `myTopic`
[source,shell,subs=+quotes]
bin/kafka-topics.sh --zookeeper zoo1.my-domain.com:2181 --delete --topic myTopic

. Verify that the topic was deleted using `kafka-topics.sh`.
+
[source,shell,subs=+quotes]
bin/kafka-topics.sh --zookeeper  _<ZookeeperAddress>_ --list
+
.Example of command to list all topics
[source,shell,subs=+quotes]
bin/kafka-topics.sh --zookeeper zoo1.my-domain.com:2181 --list

.Additional resources

* For more information about creating topics, see xref:proc-creating-a-topic-{context}[].