// Module included in the following assemblies:
//
// assembly-kafka-connect-distributed.adoc

[id='proc-deleting-connector-kafka-connect-distributed-{context}']

= Deleting connectors

This procedure will show you how to delete a connector on Kafka Connect running in distributed mode using the REST API.

.Prerequisites

* Kafka Connect is xref:proc-running-kafka-connect-distributed-{context}[running in distributed mode].

.Deleting connectors

. Verify that connector exists by sending a `GET` request to `_<KafkaConnectAddress>_:8083/connectors/_<ConnectorName>_`.
The following example shows how to do it using the `curl` utility:
+
[source,shell,subs=+quotes]
----
curl http://connect0.my-domain.com:8083/connectors
----

. DELETE the connector by sending a `DELETE` request to the `_<KafkaConnectAddress>_:8083/connectors`.
The following example shows how to do it using the `curl` utility:
+
[source,shell,subs=+quotes]
----
curl -X DELETE http://connect0.my-domain.com:8083/connectors/my-connector
----

. Verify that connector has been deleted by sending a `GET` request to `_<KafkaConnectAddress>_:8083/connectors`.
The following example shows how to do it using the `curl` utility:
+
[source,shell,subs=+quotes]
----
curl http://connect0.my-domain.com:8083/connectors
----
