// Module included in the following assemblies:
//
// assembly-upgrade.adoc

[id='proc-updating-kafka-brokers-to-new-inter-broker-protocol-version-{context}']

= Upgrading Kafka brokers to use the new inter-broker protocol version

Manually configure and restart all Kafka brokers to use the new inter-broker protocol version. After performing these steps, data is transmitted between the Kafka brokers using the new inter-broker protocol version.

Messages received are still appended to the message logs in the earlier message format version.

WARNING: Downgrading {ProductName} is not possible after completing this procedure.

.Prerequisites

* xref:proc-upgrading-zookeeper-binaries-{context}[You have updated the Zookeeper binaries.]
* xref:proc-upgrading-kafka-brokers-to-amq-streams-{context}[You have upgraded all Kafka brokers to {ProductName} {ProductVersion}]
* You are logged in to Red Hat Enterprise Linux as the `kafka` user.

.Procedure

For each Kafka broker in your {ProductName} cluster and one at a time:

. In a text editor, open the broker properties file for the Kafka broker you want to update. Broker properties files are commonly stored in the `/opt/kafka/config/` directory.

. Set the `inter.broker.protocol.version` to `{LogMsgVersHigher}`.
+
[source,shell,subs="+quotes,attributes"]
----
inter.broker.protocol.version={LogMsgVersHigher}
----

. On the command line, stop the Kafka broker that you modified:
+
[source,shell,subs=+quotes]
----
/opt/kafka/bin/kafka-server-stop.sh
jcmd | grep kafka
----

. Restart the Kafka broker that you modified:
+
[source,shell,subs=+quotes]
----
/opt/kafka/bin/kafka-server-start.sh -daemon /opt/kafka/config/server.properties
----

. Verify that the restarted Kafka broker has caught up with the partition replicas it is following. Use the `kafka-topics.sh` tool to ensure that all replicas contained in the broker are back in sync. For instructions, see xref:proc-describing-a-topic-{context}[Listing and describing topics].
