// Module included in the following assemblies:
//
// assembly-upgrade-1-1-0.adoc

[id='proc-updating-kafka-brokers-to-new-inter-broker-protocol-version-{context}']

= Updating Kafka brokers to the new inter-broker protocol version

Manually configure and restart all the Kafka brokers to use the new inter-broker protocol version (2.1). After performing these steps, data will be transmitted between the Kafka brokers using inter-broker protocol version 2.1. Messages received are still appended to the message logs in message format version 2.0. 

WARNING: Downgrading to {ProductName} 1.0.0 is not possible after completing this procedure.

NOTE: To avoid downtime, update and restart the Kafka brokers one-by-one.

.Prerequisites

* You have updated all Kafka brokers to use the previous inter-broker protocol and message format versions (2.0).
* You have upgraded all Kafka brokers to {ProductName} 1.1.0.
* You are logged in to Red Hat Enterprise Linux as the `kafka` user.

.Procedure

. In a text editor, open the broker properties file for the Kafka broker you want to update first. These files are commonly stored in the `/opt/kafka/config/` directory.

. Set the `inter.broker.protocol.version` to `2.1`.

. On the command line, restart the Kafka broker:
+
[source,shell,subs=+quotes]
----
/opt/kafka/bin/kafka-server-start.sh -daemon /opt/kafka/config/server.properties
----

. Repeat steps 1 through 3 for all Kafka brokers in your cluster.
