// Module included in the following assemblies:
//
// assembly-upgrade-1-1-0.adoc

[id='proc-upgrading-kafka-brokers-to-amq-streams-1-1-0-{context}']

= Upgrading Kafka brokers to {ProductName} 1.1.0

To upgrade to {ProductName} 1.1.0 on the host machine, download and extract the *Red Hat AMQ Streams 1.1.0* archive from the Red Hat Customer Portal. 

NOTE: This procedure is part of the xref:assembly-upgrade-1-1-0-{context}[Upgrading an {ProductName} cluster from 1.0.0 to 1.1.0] chapter. For initial installation instructions, see xref:proc-installing-amq-streams-{context}[Installing {ProductName}].

.Prerequisites
* You have updated all Kafka brokers to the previous protocol versions (2.0)
* You are logged in to Red Hat Enterprise Linux as the `kafka` user.

.Procedure

. Download the *Red Hat AMQ Streams 1.1.0* archive from the {ReleaseDownload110} area of the Customer Portal.
+
NOTE: If prompted, log in to your Red Hat account. Make sure that *1.1.0* is selected in the *Version* drop-down list.

. On the command line, create a temporary directory and extract the contents of the `amq-streams-1.1.0-bin.zip` file.
+
[source,shell,subs=+quotes]
----
mkdir /tmp/kafka-1-1-0
unzip amq-streams-1.1.0-bin.zip -d /tmp/kafka-1-1-0
----

. Move the extracted contents to the `/opt/kafka` directory that was created when {ProductName} 1.0 was installed.
+
[source,shell,subs=+quotes]
----
sudo mv /tmp/kafka-1-1-0/kafka_y.y-x.x.x/* /opt/kafka/
----

. Delete the temporary directory.
+
[source,shell,subs=+quotes]
----
rm -r /tmp/kafka-1-1-0
----