// Module included in the following assemblies:
//
// assembly-upgrade.adoc

[id='ref-kafka-versions-{context}']

= Kafka versions

{ProductName} is based on a specific version of Apache Kafka.

[options="header"]
|=======================
|{ProductName} version |Kafka version
|{ProductVersion}      |{DefaultKafkaVersion}
|=======================

Kafka's log message format version and inter-broker protocol version specify the version of the format of messages appended to broker logs and the version of protocol used between brokers in a cluster. As a result, the upgrade process involves making configuration changes to existing Kafka brokers and code changes to client applications (consumers and producers) to ensure the correct versions are used.

The following table shows the differences between Kafka versions:

include::snip-kafka-versions.adoc[]

Although Kafka versions may use the same version of Zookeeper, it is recommended that you update your Zookeeper cluster to use the newest Zookeeper binaries before proceeding with the main {ProductName} upgrade.

.Message format version

When a producer sends a message to a Kafka broker, the message is encoded using a specific format.
The format can change between Kafka releases, so messages include a version identifying which version of the format they were encoded with. You can configure a Kafka broker to convert messages from newer format versions to a given older format version before the broker appends the message to the log.

In Kafka, there are two different methods for setting the message format version:

* The `log.message.format.version` property is set on Kafka brokers.

* The `message.format.version` property is set on topics.

The default value of `message.format.version` for a  topic is defined by the `log.message.format.version` that is set on the Kafka broker. You can manually set the `message.format.version` of a topic by modifying its topic configuration.

The upgrade tasks in this section assume that the message format version is defined at the broker level by the `log.message.format.version`.
