// Module included in the following assemblies:
//
// assembly-overview.adoc

[id='admin-client-configuration-parameters-{context}']
= Admin Client configuration parameters

[cols="6",options="header",separator=¦]
|=====
¦Name ¦Description ¦Type ¦Default ¦Valid Values ¦Importance 

¦`bootstrap.servers`
a¦A list of host/port pairs to use for establishing the initial connection to the Kafka cluster. The client will make use of all servers irrespective of which servers are specified here for bootstrapping&mdash;this list only impacts the initial hosts used to discover the full set of servers. This list should be in the form `host1:port1,host2:port2,...`. Since these servers are just used for the initial connection to discover the full cluster membership (which may change dynamically), this list need not contain the full set of servers (you may want more than one, though, in case a server is down).
¦list
¦
¦
¦high

¦`ssl.key.password`
a¦The password of the private key in the key store file. This is optional for client.
¦password
¦null
¦
¦high

¦`ssl.keystore.location`
a¦The location of the key store file. This is optional for client and can be used for two-way authentication for client.
¦string
¦null
¦
¦high

¦`ssl.keystore.password`
a¦The store password for the key store file. This is optional for client and only needed if ssl.keystore.location is configured. 
¦password
¦null
¦
¦high

¦`ssl.truststore.location`
a¦The location of the trust store file. 
¦string
¦null
¦
¦high

¦`ssl.truststore.password`
a¦The password for the trust store file. If a password is not set access to the truststore is still available, but integrity checking is disabled.
¦password
¦null
¦
¦high

¦`client.id`
a¦An id string to pass to the server when making requests. The purpose of this is to be able to track the source of requests beyond just ip/port by allowing a logical application name to be included in server-side request logging.
¦string
¦""
¦
¦medium

¦`connections.max.idle.ms`
a¦Close idle connections after the number of milliseconds specified by this config.
¦long
¦300000
¦
¦medium

¦`receive.buffer.bytes`
a¦The size of the TCP receive buffer (SO_RCVBUF) to use when reading data. If the value is -1, the OS default will be used.
¦int
¦65536
¦[-1,...]
¦medium

¦`request.timeout.ms`
a¦The configuration controls the maximum amount of time the client will wait for the response of a request. If the response is not received before the timeout elapses the client will resend the request if necessary or fail the request if retries are exhausted.
¦int
¦120000
¦[0,...]
¦medium

¦`sasl.client.callback.handler.class`
a¦The fully qualified name of a SASL client callback handler class that implements the AuthenticateCallbackHandler interface.
¦class
¦null
¦
¦medium

¦`sasl.jaas.config`
a¦JAAS login context parameters for SASL connections in the format used by JAAS configuration files. JAAS configuration file format is described http://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/tutorials/LoginConfigFile.html[here]. The format for the value is: '`loginModuleClass controlFlag (optionName=optionValue)*;`'. For brokers, the config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.jaas.config=com.example.ScramLoginModule required;
¦password
¦null
¦
¦medium

¦`sasl.kerberos.service.name`
a¦The Kerberos principal name that Kafka runs as. This can be defined either in Kafka's JAAS config or in Kafka's config.
¦string
¦null
¦
¦medium

¦`sasl.login.callback.handler.class`
a¦The fully qualified name of a SASL login callback handler class that implements the AuthenticateCallbackHandler interface. For brokers, login callback handler config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.login.callback.handler.class=com.example.CustomScramLoginCallbackHandler
¦class
¦null
¦
¦medium

¦`sasl.login.class`
a¦The fully qualified name of a class that implements the Login interface. For brokers, login config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.login.class=com.example.CustomScramLogin
¦class
¦null
¦
¦medium

¦`sasl.mechanism`
a¦SASL mechanism used for client connections. This may be any mechanism for which a security provider is available. GSSAPI is the default mechanism.
¦string
¦GSSAPI
¦
¦medium

¦`security.protocol`
a¦Protocol used to communicate with brokers. Valid values are: PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL.
¦string
¦PLAINTEXT
¦
¦medium

¦`send.buffer.bytes`
a¦The size of the TCP send buffer (SO_SNDBUF) to use when sending data. If the value is -1, the OS default will be used.
¦int
¦131072
¦[-1,...]
¦medium

¦`ssl.enabled.protocols`
a¦The list of protocols enabled for SSL connections.
¦list
¦TLSv1.2,TLSv1.1,TLSv1
¦
¦medium

¦`ssl.keystore.type`
a¦The file format of the key store file. This is optional for client.
¦string
¦JKS
¦
¦medium

¦`ssl.protocol`
a¦The SSL protocol used to generate the SSLContext. Default setting is TLS, which is fine for most cases. Allowed values in recent JVMs are TLS, TLSv1.1 and TLSv1.2. SSL, SSLv2 and SSLv3 may be supported in older JVMs, but their usage is discouraged due to known security vulnerabilities.
¦string
¦TLS
¦
¦medium

¦`ssl.provider`
a¦The name of the security provider used for SSL connections. Default value is the default security provider of the JVM.
¦string
¦null
¦
¦medium

¦`ssl.truststore.type`
a¦The file format of the trust store file.
¦string
¦JKS
¦
¦medium

¦`metadata.max.age.ms`
a¦The period of time in milliseconds after which we force a refresh of metadata even if we haven't seen any partition leadership changes to proactively discover any new brokers or partitions.
¦long
¦300000
¦[0,...]
¦low

¦`metric.reporters`
a¦A list of classes to use as metrics reporters. Implementing the `org.apache.kafka.common.metrics.MetricsReporter` interface allows plugging in classes that will be notified of new metric creation. The JmxReporter is always included to register JMX statistics.
¦list
¦""
¦
¦low

¦`metrics.num.samples`
a¦The number of samples maintained to compute metrics.
¦int
¦2
¦[1,...]
¦low

¦`metrics.recording.level`
a¦The highest recording level for metrics.
¦string
¦INFO
¦[INFO, DEBUG]
¦low

¦`metrics.sample.window.ms`
a¦The window of time a metrics sample is computed over.
¦long
¦30000
¦[0,...]
¦low

¦`reconnect.backoff.max.ms`
a¦The maximum amount of time in milliseconds to wait when reconnecting to a broker that has repeatedly failed to connect. If provided, the backoff per host will increase exponentially for each consecutive connection failure, up to this maximum. After calculating the backoff increase, 20% random jitter is added to avoid connection storms.
¦long
¦1000
¦[0,...]
¦low

¦`reconnect.backoff.ms`
a¦The base amount of time to wait before attempting to reconnect to a given host. This avoids repeatedly connecting to a host in a tight loop. This backoff applies to all connection attempts by the client to a broker.
¦long
¦50
¦[0,...]
¦low

¦`retries`
a¦Setting a value greater than zero will cause the client to resend any request that fails with a potentially transient error.
¦int
¦5
¦[0,...]
¦low

¦`retry.backoff.ms`
a¦The amount of time to wait before attempting to retry a failed request. This avoids repeatedly sending requests in a tight loop under some failure scenarios.
¦long
¦100
¦[0,...]
¦low

¦`sasl.kerberos.kinit.cmd`
a¦Kerberos kinit command path.
¦string
¦/usr/bin/kinit
¦
¦low

¦`sasl.kerberos.min.time.before.relogin`
a¦Login thread sleep time between refresh attempts.
¦long
¦60000
¦
¦low

¦`sasl.kerberos.ticket.renew.jitter`
a¦Percentage of random jitter added to the renewal time.
¦double
¦0.05
¦
¦low

¦`sasl.kerberos.ticket.renew.window.factor`
a¦Login thread will sleep until the specified window factor of time from last refresh to ticket's expiry has been reached, at which time it will try to renew the ticket.
¦double
¦0.8
¦
¦low

¦`sasl.login.refresh.buffer.seconds`
a¦The amount of buffer time before credential expiration to maintain when refreshing a credential, in seconds. If a refresh would otherwise occur closer to expiration than the number of buffer seconds then the refresh will be moved up to maintain as much of the buffer time as possible. Legal values are between 0 and 3600 (1 hour); a default value of  300 (5 minutes) is used if no value is specified. This value and sasl.login.refresh.min.period.seconds are both ignored if their sum exceeds the remaining lifetime of a credential. Currently applies only to OAUTHBEARER.
¦short
¦300
¦[0,...,3600]
¦low

¦`sasl.login.refresh.min.period.seconds`
a¦The desired minimum time for the login refresh thread to wait before refreshing a credential, in seconds. Legal values are between 0 and 900 (15 minutes); a default value of 60 (1 minute) is used if no value is specified.  This value and  sasl.login.refresh.buffer.seconds are both ignored if their sum exceeds the remaining lifetime of a credential. Currently applies only to OAUTHBEARER.
¦short
¦60
¦[0,...,900]
¦low

¦`sasl.login.refresh.window.factor`
a¦Login refresh thread will sleep until the specified window factor relative to the credential's lifetime has been reached, at which time it will try to refresh the credential. Legal values are between 0.5 (50%) and 1.0 (100%) inclusive; a default value of 0.8 (80%) is used if no value is specified. Currently applies only to OAUTHBEARER.
¦double
¦0.8
¦[0.5,...,1.0]
¦low

¦`sasl.login.refresh.window.jitter`
a¦The maximum amount of random jitter relative to the credential's lifetime that is added to the login refresh thread's sleep time. Legal values are between 0 and 0.25 (25%) inclusive; a default value of 0.05 (5%) is used if no value is specified. Currently applies only to OAUTHBEARER.
¦double
¦0.05
¦[0.0,...,0.25]
¦low

¦`ssl.cipher.suites`
a¦A list of cipher suites. This is a named combination of authentication, encryption, MAC and key exchange algorithm used to negotiate the security settings for a network connection using TLS or SSL network protocol. By default all the available cipher suites are supported.
¦list
¦null
¦
¦low

¦`ssl.endpoint.identification.algorithm`
a¦The endpoint identification algorithm to validate server hostname using server certificate. 
¦string
¦https
¦
¦low

¦`ssl.keymanager.algorithm`
a¦The algorithm used by key manager factory for SSL connections. Default value is the key manager factory algorithm configured for the Java Virtual Machine.
¦string
¦SunX509
¦
¦low

¦`ssl.secure.random.implementation`
a¦The SecureRandom PRNG implementation to use for SSL cryptography operations. 
¦string
¦null
¦
¦low

¦`ssl.trustmanager.algorithm`
a¦The algorithm used by trust manager factory for SSL connections. Default value is the trust manager factory algorithm configured for the Java Virtual Machine.
¦string
¦PKIX
¦
¦low

|=====
