// Module included in the following assemblies:
//
// assembly-kafka-connect-distributed.adoc

[id='ref-kafka-connect-distributed-connector-configuration-{context}']

= Configuring connectors in distributed Kafka Connect

.HTTP REST Interface

Connectors for distributed Kafka Connect are configured using HTTP REST interface.
The REST interface listens on port 8083 by default.
It supports following endpoints:

`GET /connectors`::
Return a list of existing connectors.

`POST /connectors`::
Create a connector.
The request body has to be a JSON object with the connector configuration.

`GET /connectors/_<name>_`::
Get information about a specific connector.

`GET /connectors/_<name>_/config`::
Get configuration of a specific connector.

`PUT /connectors/_<name>_/config`::
Update the configuration of a specific connector.

`GET /connectors/_<name>_/status`::
Get the status of a specific connector.

`PUT /connectors/_<name>_/pause`::
Pause the connector and all its tasks.
The connector will stop processing any messages.

`PUT /connectors/_<name>_/resume`::
Resume a paused connector.

`POST /connectors/_<name>_/restart`::
Restart a connector in case it has failed.

`DELETE /connectors/_<name>_`::
Delete a connector.

`GET /connector-plugins`::
Get a list of all supported connector plugins.

.Connector configuration

Most configuration options are connector specific and included in the documentation for the connectors. The following fields are common for all connectors.

`name`:: 
Name of the connector.
Must be unique within a given Kafka Connect instance.

`connector.class`::
Class of the connector plugin.
For example `org.apache.kafka.connect.file.FileStreamSinkConnector`.

`tasks.max`::
The maximum number of tasks used by this connector.
Tasks are used by the connector to parallelise its work.
Connetors may create fewer tasks than specified.

`key.converter`::
Class used to convert message keys to and from Kafka format.
This overrides the default value set by the Kafka Connect configuration.
For example, `org.apache.kafka.connect.json.JsonConverter`.

`value.converter`::
Class used to convert message payloads to and from Kafka format.
This overrides the default value set by the Kafka Connect configuration.
For example, `org.apache.kafka.connect.json.JsonConverter`.

Additionally, one of the following options must be set for sink connectors:

`topics`:: 
A comma-separated list of topics used as input.

`topics.regex`::
A Java regular expression of topics used as input.

For all other options, see the documentation for the specific connector.

AMQ Streams includes example connector configuration files.
They can be found in `config/connect-file-sink.properties` and `config/connect-file-source.properties` in the AMQ Streams installation directory.
