// Module included in the following assemblies:
//
// assembly-kafka-connect-standalone.adoc

[id='ref-kafka-connect-standalone-connector-configuration-{context}']

= Configuring connectors in Kafka Connect in standalone mode

You can configure connector plug-ins for Kafka Connect in standalone mode using properties files. Most configuration options are specific to each connector. The following options apply to all connectors:

``name``::
The name of the connector, which must be unique within the current Kafka Connect instance.

``connector.class``::
The class of the connector plug-in. For example, ``org.apache.kafka.connect.file.FileStreamSinkConnector``.

``tasks.max``::
The maximum number of tasks that the specified connector can use. Tasks enable the connector to perform work in parallel. The connector might create fewer tasks than specified.

``key.converter``::
The class used to convert message keys to and from Kafka format. This overrides the default value set by the Kafka Connect configuration. For example, ``org.apache.kafka.connect.json.JsonConverter``.

``value.converter``::
The class used to convert message payloads to and from Kafka format. This overrides the default value set by the Kafka Connect configuration. For example, ``org.apache.kafka.connect.json.JsonConverter``.

Additionally, you must set at least one of the following options for sink connectors:

``topics``::
A comma-separated list of topics used as input.

``topics.regex``::
A Java regular expression of topics used as input.

For all other options, see the documentation for the available connectors.

{ProductName} includes example connector configuration files – see ``config/connect-file-sink.properties`` and ``config/connect-file-source.properties`` in the {ProductName} installation directory.
