// Module included in the following assemblies:
//
// assembly-overview.adoc

[id='topic-configuration-parameters-{context}']
= Topic configuration parameters

[cols="30,40,10,10,10"",options="header",separator=¦]
|=====
¦Name ¦Description ¦Type ¦Default ¦Valid Values ¦Server Default Property 

5+h¦medium importance


¦`cleanup.policy`
a¦A string that is either "delete" or "compact". This string designates the retention policy to use on old log segments. The default policy ("delete") will discard old segments when their retention time or size limit has been reached. The "compact" setting will enable #compaction[log compaction] on the topic.
¦list
¦delete
¦[compact, delete]
¦log.cleanup.policy



¦`compression.type`
a¦Specify the final compression type for a given topic. This configuration accepts the standard compression codecs ('gzip', 'snappy', 'lz4', 'zstd'). It additionally accepts 'uncompressed' which is equivalent to no compression; and 'producer' which means retain the original compression codec set by the producer.
¦string
¦producer
¦[uncompressed, zstd, lz4, snappy, gzip, producer]
¦compression.type



¦`delete.retention.ms`
a¦The amount of time to retain delete tombstone markers for #compaction[log compacted] topics. This setting also gives a bound on the time in which a consumer must complete a read if they begin from offset 0 to ensure that they get a valid snapshot of the final stage (otherwise delete tombstones may be collected before they complete their scan).
¦long
¦86400000
¦[0,...]
¦log.cleaner.delete.retention.ms



¦`file.delete.delay.ms`
a¦The time to wait before deleting a file from the filesystem.
¦long
¦60000
¦[0,...]
¦log.segment.delete.delay.ms



¦`flush.messages`
a¦This setting allows specifying an interval at which we will force an fsync of data written to the log. For example if this was set to 1 we would fsync after every message; if it were 5 we would fsync after every five messages. In general we recommend you not set this and use replication for durability and allow the operating system's background flush capabilities as it is more efficient. This setting can be overridden on a per-topic basis (see #topicconfigs[the per-topic configuration section]).
¦long
¦9223372036854775807
¦[0,...]
¦log.flush.interval.messages



¦`flush.ms`
a¦This setting allows specifying a time interval at which we will force an fsync of data written to the log. For example if this was set to 1000 we would fsync after 1000 ms had passed. In general we recommend you not set this and use replication for durability and allow the operating system's background flush capabilities as it is more efficient.
¦long
¦9223372036854775807
¦[0,...]
¦log.flush.interval.ms



¦`follower.replication.throttled.replicas`
a¦A list of replicas for which log replication should be throttled on the follower side. The list should describe a set of replicas in the form [PartitionId]:[BrokerId],[PartitionId]:[BrokerId]:... or alternatively the wildcard '*' can be used to throttle all replicas for this topic.
¦list
¦""
¦[partitionId],[brokerId]:[partitionId],[brokerId]:...
¦follower.replication.throttled.replicas



¦`index.interval.bytes`
a¦This setting controls how frequently Kafka adds an index entry to its offset index. The default setting ensures that we index a message roughly every 4096 bytes. More indexing allows reads to jump closer to the exact position in the log but makes the index larger. You probably don't need to change this.
¦int
¦4096
¦[0,...]
¦log.index.interval.bytes



¦`leader.replication.throttled.replicas`
a¦A list of replicas for which log replication should be throttled on the leader side. The list should describe a set of replicas in the form [PartitionId]:[BrokerId],[PartitionId]:[BrokerId]:... or alternatively the wildcard '*' can be used to throttle all replicas for this topic.
¦list
¦""
¦[partitionId],[brokerId]:[partitionId],[brokerId]:...
¦leader.replication.throttled.replicas



¦`max.message.bytes`
a¦
The largest record batch size allowed by Kafka. If this is increased and there are consumers older than 0.10.2, the consumers' fetch size must also be increased so that the they can fetch record batches this large.

In the latest message format version, records are always grouped into batches for efficiency. In previous message format versions, uncompressed records are not grouped into batches and this limit only applies to a single record in that case.

¦int
¦1000012
¦[0,...]
¦message.max.bytes



¦`message.format.version`
a¦Specify the message format version the broker will use to append messages to the logs. The value should be a valid ApiVersion. Some examples are: 0.8.2, 0.9.0.0, 0.10.0, check ApiVersion for more details. By setting a particular message format version, the user is certifying that all the existing messages on disk are smaller or equal than the specified version. Setting this value incorrectly will cause consumers with older versions to break as they will receive messages with a format that they don't understand.
¦string
¦2.1-IV2
¦kafka.api.ApiVersionValidator$@2a17b7b6
¦log.message.format.version



¦`message.timestamp.difference.max.ms`
a¦The maximum difference allowed between the timestamp when a broker receives a message and the timestamp specified in the message. If message.timestamp.type=CreateTime, a message will be rejected if the difference in timestamp exceeds this threshold. This configuration is ignored if message.timestamp.type=LogAppendTime.
¦long
¦9223372036854775807
¦[0,...]
¦log.message.timestamp.difference.max.ms



¦`message.timestamp.type`
a¦Define whether the timestamp in the message is message create time or log append time. The value should be either `CreateTime` or `LogAppendTime`.
¦string
¦CreateTime
¦[CreateTime, LogAppendTime]
¦log.message.timestamp.type



¦`min.cleanable.dirty.ratio`
a¦This configuration controls how frequently the log compactor will attempt to clean the log (assuming #compaction[log compaction] is enabled). By default we will avoid cleaning a log where more than 50% of the log has been compacted. This ratio bounds the maximum space wasted in the log by duplicates (at 50% at most 50% of the log could be duplicates). A higher ratio will mean fewer, more efficient cleanings but will mean more wasted space in the log.
¦double
¦0.5
¦[0,...,1]
¦log.cleaner.min.cleanable.ratio



¦`min.compaction.lag.ms`
a¦The minimum time a message will remain uncompacted in the log. Only applicable for logs that are being compacted.
¦long
¦0
¦[0,...]
¦log.cleaner.min.compaction.lag.ms



¦`min.insync.replicas`
a¦When a producer sets acks to "all" (or "-1"), this configuration specifies the minimum number of replicas that must acknowledge a write for the write to be considered successful. If this minimum cannot be met, then the producer will raise an exception (either NotEnoughReplicas or NotEnoughReplicasAfterAppend).
When used together, `min.insync.replicas` and `acks` allow you to enforce greater durability guarantees. A typical scenario would be to create a topic with a replication factor of 3, set `min.insync.replicas` to 2, and produce with `acks` of "all". This will ensure that the producer raises an exception if a majority of replicas do not receive a write.
¦int
¦1
¦[1,...]
¦min.insync.replicas



¦`preallocate`
a¦True if we should preallocate the file on disk when creating a new log segment.
¦boolean
¦false
¦
¦log.preallocate



¦`retention.bytes`
a¦This configuration controls the maximum size a partition (which consists of log segments) can grow to before we will discard old log segments to free up space if we are using the "delete" retention policy. By default there is no size limit only a time limit. Since this limit is enforced at the partition level, multiply it by the number of partitions to compute the topic retention in bytes.
¦long
¦-1
¦
¦log.retention.bytes



¦`retention.ms`
a¦This configuration controls the maximum time we will retain a log before we will discard old log segments to free up space if we are using the "delete" retention policy. This represents an SLA on how soon consumers must read their data. If set to -1, no time limit is applied.
¦long
¦604800000
¦
¦log.retention.ms



¦`segment.bytes`
a¦This configuration controls the segment file size for the log. Retention and cleaning is always done a file at a time so a larger segment size means fewer files but less granular control over retention.
¦int
¦1073741824
¦[14,...]
¦log.segment.bytes



¦`segment.index.bytes`
a¦This configuration controls the size of the index that maps offsets to file positions. We preallocate this index file and shrink it only after log rolls. You generally should not need to change this setting.
¦int
¦10485760
¦[0,...]
¦log.index.size.max.bytes



¦`segment.jitter.ms`
a¦The maximum random jitter subtracted from the scheduled segment roll time to avoid thundering herds of segment rolling.
¦long
¦0
¦[0,...]
¦log.roll.jitter.ms



¦`segment.ms`
a¦This configuration controls the period of time after which Kafka will force the log to roll even if the segment file isn't full to ensure that retention can delete or compact old data.
¦long
¦604800000
¦[1,...]
¦log.roll.ms



¦`unclean.leader.election.enable`
a¦Indicates whether to enable replicas not in the ISR set to be elected as leader as a last resort, even though doing so may result in data loss.
¦boolean
¦false
¦
¦unclean.leader.election.enable

5+h¦low importance


¦`message.downconversion.enable`
a¦This configuration controls whether down-conversion of message formats is enabled to satisfy consume requests. When set to `false`, broker will not perform down-conversion for consumers expecting an older message format. The broker responds with `UNSUPPORTED_VERSION` error for consume requests from such older clients. This configurationdoes not apply to any message format conversion that might be required for replication to followers.
¦boolean
¦true
¦
¦log.message.downconversion.enable

|=====
