// Module included in the following assemblies:
//
// assembly-overview.adoc

[id='consumer-configuration-parameters-{context}']
= Consumer configuration parameters

[cols="6",options="header",separator=¦]
|=====
¦Name ¦Description ¦Type ¦Default ¦Valid Values ¦Importance 

¦`key.deserializer`
a¦Deserializer class for key that implements the `org.apache.kafka.common.serialization.Deserializer` interface.
¦class
¦
¦
¦high

¦`value.deserializer`
a¦Deserializer class for value that implements the `org.apache.kafka.common.serialization.Deserializer` interface.
¦class
¦
¦
¦high

¦`bootstrap.servers`
a¦A list of host/port pairs to use for establishing the initial connection to the Kafka cluster. The client will make use of all servers irrespective of which servers are specified here for bootstrapping&mdash;this list only impacts the initial hosts used to discover the full set of servers. This list should be in the form `host1:port1,host2:port2,...`. Since these servers are just used for the initial connection to discover the full cluster membership (which may change dynamically), this list need not contain the full set of servers (you may want more than one, though, in case a server is down).
¦list
¦""
¦non-null value
¦high

¦`fetch.min.bytes`
a¦The minimum amount of data the server should return for a fetch request. If insufficient data is available the request will wait for that much data to accumulate before answering the request. The default setting of 1 byte means that fetch requests are answered as soon as a single byte of data is available or the fetch request times out waiting for data to arrive. Setting this to something greater than 1 will cause the server to wait for larger amounts of data to accumulate which can improve server throughput a bit at the cost of some additional latency.
¦int
¦1
¦[0,...]
¦high

¦`group.id`
a¦A unique string that identifies the consumer group this consumer belongs to. This property is required if the consumer uses either the group management functionality by using `subscribe(topic)` or the Kafka-based offset management strategy.
¦string
¦""
¦
¦high

¦`heartbeat.interval.ms`
a¦The expected time between heartbeats to the consumer coordinator when using Kafka's group management facilities. Heartbeats are used to ensure that the consumer's session stays active and to facilitate rebalancing when new consumers join or leave the group. The value must be set lower than `session.timeout.ms`, but typically should be set no higher than 1/3 of that value. It can be adjusted even lower to control the expected time for normal rebalances.
¦int
¦3000
¦
¦high

¦`max.partition.fetch.bytes`
a¦The maximum amount of data per-partition the server will return. Records are fetched in batches by the consumer. If the first record batch in the first non-empty partition of the fetch is larger than this limit, the batch will still be returned to ensure that the consumer can make progress. The maximum record batch size accepted by the broker is defined via `message.max.bytes` (broker config) or `max.message.bytes` (topic config). See fetch.max.bytes for limiting the consumer request size.
¦int
¦1048576
¦[0,...]
¦high

¦`session.timeout.ms`
a¦The timeout used to detect consumer failures when using Kafka's group management facility. The consumer sends periodic heartbeats to indicate its liveness to the broker. If no heartbeats are received by the broker before the expiration of this session timeout, then the broker will remove this consumer from the group and initiate a rebalance. Note that the value must be in the allowable range as configured in the broker configuration by `group.min.session.timeout.ms` and `group.max.session.timeout.ms`.
¦int
¦10000
¦
¦high

¦`ssl.key.password`
a¦The password of the private key in the key store file. This is optional for client.
¦password
¦null
¦
¦high

¦`ssl.keystore.location`
a¦The location of the key store file. This is optional for client and can be used for two-way authentication for client.
¦string
¦null
¦
¦high

¦`ssl.keystore.password`
a¦The store password for the key store file. This is optional for client and only needed if ssl.keystore.location is configured. 
¦password
¦null
¦
¦high

¦`ssl.truststore.location`
a¦The location of the trust store file. 
¦string
¦null
¦
¦high

¦`ssl.truststore.password`
a¦The password for the trust store file. If a password is not set access to the truststore is still available, but integrity checking is disabled.
¦password
¦null
¦
¦high

¦`auto.offset.reset`
a¦What to do when there is no initial offset in Kafka or if the current offset does not exist any more on the server (e.g. because that data has been deleted): 

* earliest: automatically reset the offset to the earliest offset
* latest: automatically reset the offset to the latest offset
* none: throw exception to the consumer if no previous offset is found for the consumer's group
* anything else: throw exception to the consumer.
¦string
¦latest
¦[latest, earliest, none]
¦medium

¦`connections.max.idle.ms`
a¦Close idle connections after the number of milliseconds specified by this config.
¦long
¦540000
¦
¦medium

¦`default.api.timeout.ms`
a¦Specifies the timeout (in milliseconds) for consumer APIs that could block. This configuration is used as the default timeout for all consumer operations that do not explicitly accept a `timeout` parameter.
¦int
¦60000
¦[0,...]
¦medium

¦`enable.auto.commit`
a¦If true the consumer's offset will be periodically committed in the background.
¦boolean
¦true
¦
¦medium

¦`exclude.internal.topics`
a¦Whether records from internal topics (such as offsets) should be exposed to the consumer. If set to `true` the only way to receive records from an internal topic is subscribing to it.
¦boolean
¦true
¦
¦medium

¦`fetch.max.bytes`
a¦The maximum amount of data the server should return for a fetch request. Records are fetched in batches by the consumer, and if the first record batch in the first non-empty partition of the fetch is larger than this value, the record batch will still be returned to ensure that the consumer can make progress. As such, this is not a absolute maximum. The maximum record batch size accepted by the broker is defined via `message.max.bytes` (broker config) or `max.message.bytes` (topic config). Note that the consumer performs multiple fetches in parallel.
¦int
¦52428800
¦[0,...]
¦medium

¦`isolation.level`
a¦
Controls how to read messages written transactionally. If set to `read_committed`, consumer.poll() will only return transactional messages which have been committed. If set to `read_uncommitted`' (the default), consumer.poll() will return all messages, even transactional messages which have been aborted. Non-transactional messages will be returned unconditionally in either mode.</p> 
Messages will always be returned in offset order. Hence, in  `read_committed` mode, consumer.poll() will only return messages up to the last stable offset (LSO), which is the one less than the offset of the first open transaction. In particular any messages appearing after messages belonging to ongoing transactions will be withheld until the relevant transaction has been completed. As a result, `read_committed` consumers will not be able to read up to the high watermark when there are in flight transactions.</p>
 Further, when in `read_committed</mode> the seekToEnd method will return the LSO
¦string
¦read_uncommitted
¦[read_committed, read_uncommitted]
¦medium

¦`max.poll.interval.ms`
a¦The maximum delay between invocations of poll() when using consumer group management. This places an upper bound on the amount of time that the consumer can be idle before fetching more records. If poll() is not called before expiration of this timeout, then the consumer is considered failed and the group will rebalance in order to reassign the partitions to another member. 
¦int
¦300000
¦[1,...]
¦medium

¦`max.poll.records`
a¦The maximum number of records returned in a single call to poll().
¦int
¦500
¦[1,...]
¦medium

¦`partition.assignment.strategy`
a¦The class name of the partition assignment strategy that the client will use to distribute partition ownership amongst consumer instances when group management is used
¦list
¦class org.apache.kafka.clients.consumer.RangeAssignor
¦non-null value
¦medium

¦`receive.buffer.bytes`
a¦The size of the TCP receive buffer (SO_RCVBUF) to use when reading data. If the value is -1, the OS default will be used.
¦int
¦65536
¦[-1,...]
¦medium

¦`request.timeout.ms`
a¦The configuration controls the maximum amount of time the client will wait for the response of a request. If the response is not received before the timeout elapses the client will resend the request if necessary or fail the request if retries are exhausted.
¦int
¦30000
¦[0,...]
¦medium

¦`sasl.client.callback.handler.class`
a¦The fully qualified name of a SASL client callback handler class that implements the AuthenticateCallbackHandler interface.
¦class
¦null
¦
¦medium

¦`sasl.jaas.config`
a¦JAAS login context parameters for SASL connections in the format used by JAAS configuration files. JAAS configuration file format is described http://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/tutorials/LoginConfigFile.html[here]. The format for the value is: '`loginModuleClass controlFlag (optionName=optionValue)*;`'. For brokers, the config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.jaas.config=com.example.ScramLoginModule required;
¦password
¦null
¦
¦medium

¦`sasl.kerberos.service.name`
a¦The Kerberos principal name that Kafka runs as. This can be defined either in Kafka's JAAS config or in Kafka's config.
¦string
¦null
¦
¦medium

¦`sasl.login.callback.handler.class`
a¦The fully qualified name of a SASL login callback handler class that implements the AuthenticateCallbackHandler interface. For brokers, login callback handler config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.login.callback.handler.class=com.example.CustomScramLoginCallbackHandler
¦class
¦null
¦
¦medium

¦`sasl.login.class`
a¦The fully qualified name of a class that implements the Login interface. For brokers, login config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.login.class=com.example.CustomScramLogin
¦class
¦null
¦
¦medium

¦`sasl.mechanism`
a¦SASL mechanism used for client connections. This may be any mechanism for which a security provider is available. GSSAPI is the default mechanism.
¦string
¦GSSAPI
¦
¦medium

¦`security.protocol`
a¦Protocol used to communicate with brokers. Valid values are: PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL.
¦string
¦PLAINTEXT
¦
¦medium

¦`send.buffer.bytes`
a¦The size of the TCP send buffer (SO_SNDBUF) to use when sending data. If the value is -1, the OS default will be used.
¦int
¦131072
¦[-1,...]
¦medium

¦`ssl.enabled.protocols`
a¦The list of protocols enabled for SSL connections.
¦list
¦TLSv1.2,TLSv1.1,TLSv1
¦
¦medium

¦`ssl.keystore.type`
a¦The file format of the key store file. This is optional for client.
¦string
¦JKS
¦
¦medium

¦`ssl.protocol`
a¦The SSL protocol used to generate the SSLContext. Default setting is TLS, which is fine for most cases. Allowed values in recent JVMs are TLS, TLSv1.1 and TLSv1.2. SSL, SSLv2 and SSLv3 may be supported in older JVMs, but their usage is discouraged due to known security vulnerabilities.
¦string
¦TLS
¦
¦medium

¦`ssl.provider`
a¦The name of the security provider used for SSL connections. Default value is the default security provider of the JVM.
¦string
¦null
¦
¦medium

¦`ssl.truststore.type`
a¦The file format of the trust store file.
¦string
¦JKS
¦
¦medium

¦`auto.commit.interval.ms`
a¦The frequency in milliseconds that the consumer offsets are auto-committed to Kafka if `enable.auto.commit` is set to `true`.
¦int
¦5000
¦[0,...]
¦low

¦`check.crcs`
a¦Automatically check the CRC32 of the records consumed. This ensures no on-the-wire or on-disk corruption to the messages occurred. This check adds some overhead, so it may be disabled in cases seeking extreme performance.
¦boolean
¦true
¦
¦low

¦`client.id`
a¦An id string to pass to the server when making requests. The purpose of this is to be able to track the source of requests beyond just ip/port by allowing a logical application name to be included in server-side request logging.
¦string
¦""
¦
¦low

¦`fetch.max.wait.ms`
a¦The maximum amount of time the server will block before answering the fetch request if there isn't sufficient data to immediately satisfy the requirement given by fetch.min.bytes.
¦int
¦500
¦[0,...]
¦low

¦`interceptor.classes`
a¦A list of classes to use as interceptors. Implementing the `org.apache.kafka.clients.consumer.ConsumerInterceptor` interface allows you to intercept (and possibly mutate) records received by the consumer. By default, there are no interceptors.
¦list
¦""
¦non-null value
¦low

¦`metadata.max.age.ms`
a¦The period of time in milliseconds after which we force a refresh of metadata even if we haven't seen any partition leadership changes to proactively discover any new brokers or partitions.
¦long
¦300000
¦[0,...]
¦low

¦`metric.reporters`
a¦A list of classes to use as metrics reporters. Implementing the `org.apache.kafka.common.metrics.MetricsReporter` interface allows plugging in classes that will be notified of new metric creation. The JmxReporter is always included to register JMX statistics.
¦list
¦""
¦non-null value
¦low

¦`metrics.num.samples`
a¦The number of samples maintained to compute metrics.
¦int
¦2
¦[1,...]
¦low

¦`metrics.recording.level`
a¦The highest recording level for metrics.
¦string
¦INFO
¦[INFO, DEBUG]
¦low

¦`metrics.sample.window.ms`
a¦The window of time a metrics sample is computed over.
¦long
¦30000
¦[0,...]
¦low

¦`reconnect.backoff.max.ms`
a¦The maximum amount of time in milliseconds to wait when reconnecting to a broker that has repeatedly failed to connect. If provided, the backoff per host will increase exponentially for each consecutive connection failure, up to this maximum. After calculating the backoff increase, 20% random jitter is added to avoid connection storms.
¦long
¦1000
¦[0,...]
¦low

¦`reconnect.backoff.ms`
a¦The base amount of time to wait before attempting to reconnect to a given host. This avoids repeatedly connecting to a host in a tight loop. This backoff applies to all connection attempts by the client to a broker.
¦long
¦50
¦[0,...]
¦low

¦`retry.backoff.ms`
a¦The amount of time to wait before attempting to retry a failed request to a given topic partition. This avoids repeatedly sending requests in a tight loop under some failure scenarios.
¦long
¦100
¦[0,...]
¦low

¦`sasl.kerberos.kinit.cmd`
a¦Kerberos kinit command path.
¦string
¦/usr/bin/kinit
¦
¦low

¦`sasl.kerberos.min.time.before.relogin`
a¦Login thread sleep time between refresh attempts.
¦long
¦60000
¦
¦low

¦`sasl.kerberos.ticket.renew.jitter`
a¦Percentage of random jitter added to the renewal time.
¦double
¦0.05
¦
¦low

¦`sasl.kerberos.ticket.renew.window.factor`
a¦Login thread will sleep until the specified window factor of time from last refresh to ticket's expiry has been reached, at which time it will try to renew the ticket.
¦double
¦0.8
¦
¦low

¦`sasl.login.refresh.buffer.seconds`
a¦The amount of buffer time before credential expiration to maintain when refreshing a credential, in seconds. If a refresh would otherwise occur closer to expiration than the number of buffer seconds then the refresh will be moved up to maintain as much of the buffer time as possible. Legal values are between 0 and 3600 (1 hour); a default value of  300 (5 minutes) is used if no value is specified. This value and sasl.login.refresh.min.period.seconds are both ignored if their sum exceeds the remaining lifetime of a credential. Currently applies only to OAUTHBEARER.
¦short
¦300
¦[0,...,3600]
¦low

¦`sasl.login.refresh.min.period.seconds`
a¦The desired minimum time for the login refresh thread to wait before refreshing a credential, in seconds. Legal values are between 0 and 900 (15 minutes); a default value of 60 (1 minute) is used if no value is specified.  This value and  sasl.login.refresh.buffer.seconds are both ignored if their sum exceeds the remaining lifetime of a credential. Currently applies only to OAUTHBEARER.
¦short
¦60
¦[0,...,900]
¦low

¦`sasl.login.refresh.window.factor`
a¦Login refresh thread will sleep until the specified window factor relative to the credential's lifetime has been reached, at which time it will try to refresh the credential. Legal values are between 0.5 (50%) and 1.0 (100%) inclusive; a default value of 0.8 (80%) is used if no value is specified. Currently applies only to OAUTHBEARER.
¦double
¦0.8
¦[0.5,...,1.0]
¦low

¦`sasl.login.refresh.window.jitter`
a¦The maximum amount of random jitter relative to the credential's lifetime that is added to the login refresh thread's sleep time. Legal values are between 0 and 0.25 (25%) inclusive; a default value of 0.05 (5%) is used if no value is specified. Currently applies only to OAUTHBEARER.
¦double
¦0.05
¦[0.0,...,0.25]
¦low

¦`ssl.cipher.suites`
a¦A list of cipher suites. This is a named combination of authentication, encryption, MAC and key exchange algorithm used to negotiate the security settings for a network connection using TLS or SSL network protocol. By default all the available cipher suites are supported.
¦list
¦null
¦
¦low

¦`ssl.endpoint.identification.algorithm`
a¦The endpoint identification algorithm to validate server hostname using server certificate. 
¦string
¦https
¦
¦low

¦`ssl.keymanager.algorithm`
a¦The algorithm used by key manager factory for SSL connections. Default value is the key manager factory algorithm configured for the Java Virtual Machine.
¦string
¦SunX509
¦
¦low

¦`ssl.secure.random.implementation`
a¦The SecureRandom PRNG implementation to use for SSL cryptography operations. 
¦string
¦null
¦
¦low

¦`ssl.trustmanager.algorithm`
a¦The algorithm used by trust manager factory for SSL connections. Default value is the trust manager factory algorithm configured for the Java Virtual Machine.
¦string
¦PKIX
¦
¦low

|=====
