// This assembly is included in the following assemblies:
//
// assembly-kafka-exporter.adoc
[id='con-metrics-kafka-exporter-alerts{context}']

= Kafka Exporter alerting rule examples

The sample alert notification rules specific to Kafka Exporter are as follows:

`UnderReplicatedPartition`:: An alert to warn that a topic is under-replicated and the broker is not replicating enough partitions.
The default configuration is for an alert if there are one or more under-replicated partitions for a topic.
The alert might signify that a Kafka instance is down or the Kafka cluster is overloaded.
A planned restart of the Kafka broker may be required to restart the replication process.

`TooLargeConsumerGroupLag`:: An alert to warn that the lag on a consumer group is too large for a specific topic partition.
The default configuration is 1000 records.
A large lag might indicate that consumers are too slow and are falling behind the producers.

`NoMessageForTooLong`:: An alert to warn that a topic has not received messages for a period of time.
The default configuration for the time period is 10 minutes.
The delay might be a result of a configuration issue preventing a producer from publishing messages to the topic.

You can adapt alerting rules according to your specific needs.

.Additional resources

For more information about setting up alerting rules, see {PrometheusConfig} in the Prometheus documentation.
