// Module included in the following assemblies:
//
// assembly-oauth.adoc

[id='con-oauth-authentication-flow-{context}']
= {oauth} authentication mechanism

The Kafka _SASL OAUTHBEARER_ mechanism is used to establish authenticated sessions with a Kafka broker.

A Kafka client initiates a session with the Kafka broker using the _SASL OAUTHBEARER_ mechanism for credentials exchange, where credentials take the form of an access token.

Kafka brokers and clients need to be configured to use {oauth}.

== Configuring {oauth} with properties or variables

You can configure {oauth} settings using Java Authentication and Authorization Service (JAAS) properties or environment variables.

* JAAS properties are configured in the `server.properties` configuration file, and passed as key-values pairs of the `listener.name._<listener-name>_.oauthbearer.sasl.jaas.config` property.
* Using environment variables, you still need the `listener.name._<listener-name>_.oauthbearer.sasl.jaas.config` in the `server.properties` file, but you can omit the properties.
+
You can use capitalized or upper-case environment variable naming conventions.
