// Module included in the following assemblies:
//
// assembly-oauth.adoc

[id='con-oauth-authentication-broker-{context}']
= {oauth} Kafka broker configuration

Kafka broker configuration for {oauth} involves:

* Client configuration (for the Kafka broker) on an authorization server
* {oauth} authentication configuration in the Kafka cluster

NOTE: In relation to the authorization server, Kafka brokers and Kafka clients are both regarded as {oauth} clients.

== {oauth} client configuration on an authorization server

To configure a Kafka broker to validate the token received during session initiation,
the recommended approach is to create a {oauth} _client_ definition in an authorization server, configured as _confidential_, with client credentials enabled:

* Client ID of `kafka`
* Client ID and secret as the authentication mechanism

== {oauth} authentication configuration in the Kafka cluster

To use {oauth} authentication in the Kafka cluster, you enable a listener configuration for your Kafka cluster in the Kafka `server.properties` file.
A minimum configuration is required.
You can also configure a TLS listener, where TLS is used for inter-broker communication.

The minimum configuration shown here applies a _global_ listener configuration.
This means that inter-broker communication goes through the same listener as application clients.

To enable {oauth} configuration for a specific listener, you specify `listener.name.clients.sasl.enabled.mechanisms` instead of `sasl.enabled.mechanisms`,
which is shown in the example TLS listener configuration.

.Minimum listener configuration for {oauth} authentication
[source,env,subs="+quotes, attributes"]
----
sasl.enabled.mechanisms=OAUTHBEARER <1>
listeners=CLIENT://0.0.0.0:9092 <2>
listener.security.protocol.map=CLIENT:SASL_PLAINTEXT <3>
listener.name.client.sasl.enabled.mechanisms=OAUTHBEARER <4>
sasl.mechanism.inter.broker.protocol=OAUTHBEARER <5>
inter.broker.listener.name=CLIENT <6>
listener.name.client.oauthbearer.sasl.server.callback.handler.class=io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler <7>
listener.name.client.oauthbearer.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \ <8>
  oauth.valid.issuer.uri="https://_<auth-server-address>_" \ <9>
  oauth.jwks.endpoint.uri="https://_<auth-server-address>_/jwks" \ <10>
  oauth.username.claim="preferred_username"  \ <11>
  oauth.client.id="kafka-broker" \ <12>
  oauth.client.secret="kafka-secret" \ <13>
  oauth.token.endpoint.uri="https://_<auth-server-address>_/token" ; <14>
listener.name.clients.oauthbearer.sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler  <15>
----
<1> Enables the _OAUTHBEARER as SASL_ mechanism for credentials exchange over SASL.
<2> Configures a listener for client applications, replacing `kafka` with a valid hostname, resolvable by clients.
<3> Specifies the channel protocol for the listener. `SASL_SSL` is for TLS. `SASL_PLAINTEXT` is used for an unencrypted connection (no TLS), but there is risk of eavesdropping and interception at the TCP connection layer.
<4> Specifies _OAUTHBEARER as SASL_ for client listeners.
<5> Specifies _OAUTHBEARER as SASL_ for inter-broker communication.
<6> Specifies the listener for inter-broker communication.
<7> Configures {oauth} authentication on the client listener.
<8> Configures authentication settings for client and inter-broker communication.
The `oauth.client.id`, `oauth.client.secret` and `auth.token.endpoint.uri` properties relate to inter-broker configuration.
<9> A valid issuer URI. Only access tokens issued by this issuer will be accepted.
<10> The JWKS endpoint URL. For example, _\https://<auth-server-address>/auth/realms/master/protocol/openid-connect/certs_.
<11> The user name profile claim (or key) that contains the actual user name in the token.
The user name is the _principal_ used to identify the user.
The value will depend on the authentication flow and the authorization server used.
<12> Client ID of the Kafka broker, which is the same for all brokers. This is the xref:proc-oauth-server-config-{context}[client registered with the authorization server as `kafka-broker`].
<13> Secret for the Kafka broker, which is the same for all brokers.
<14> The {oauth} token endpoint URL to your authorization server. For production, always use HTTPs.
<15> Enables (and is only required) for {oauth} authentication for inter-broker communication.

.TLS listener configuration for {oauth} authentication
[source,env,subs="+quotes, attributes"]
----
sasl.enabled.mechanisms=
listeners=REPLICATION://kafka:9091,CLIENT://kafka:9092 <1>
listener.security.protocol.map=REPLICATION:SSL,CLIENT:SASL_PLAINTEXT <2>
listener.name.client.sasl.enabled.mechanisms=OAUTHBEARER
inter.broker.listener.name=REPLICATION
ssl.keystore.password=_<my-keystore-password>_ <3>
ssl.truststore.password=_<my-truststore-password>_
ssl.keystore.type=PKCS12
ssl.truststore.type=PKCS12
ssl.endpoint.identification.algorithm=HTTPS
ssl.secure.random.implementation=SHA1PRNG
listener.name.replication.ssl.keystore.location=_<path-to-keystore-p12>_ <4>
listener.name.replication.ssl.truststore.location=_<path-to-truststore-p12>_ <5>
listener.name.replication.ssl.client.auth=required <6>
listener.name.client.oauthbearer.sasl.server.callback.handler.class=io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
listener.name.client.oauthbearer.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
  oauth.valid.issuer.uri="https://_<auth-server-address>_" \
  oauth.jwks.endpoint.uri="https://_<auth-server-address>_/jwks" \
  oauth.username.claim="preferred_username"  \
  unsecuredLoginStringClaim_sub="thePrincipalName" ; <7>
----
<1> Separate configurations are required for inter-broker communication and client applications.
<2> Separate channel protocols are required for inter-broker communication and client applications.
<3> The `ssl.` properties define the TLS configuration.
<4> Path to the keystore for the listener.
<5> Path to the truststore for the listener.
<6> Specifies that TLS is required for the listener.
<7> Configures the listener so that TLS client authentication with certificates is used for inter-broker communication.


== Fast local JWT token validation configuration

Fast local JWT token validation checks a JWT token signature locally.

The local check ensures a token:

* Conforms to type (`oauth`)
* Is valid (not expired)
* Has an issuer that matches a valid issuer URI

You specify a _valid issuer URI_ when you configure the listener environment variables, so that any tokens not issued by the authorization server are rejected.

The authorization server does not need to be contacted during fast local JWT token validation.
You activate fast local JWT token validation by specifying a _JWKs endpoint URI_ exposed by the {oauth} authorization server.
The endpoint contains the public keys used to validate signed JWT tokens, which are sent as credentials by Kafka clients.

NOTE: All communication with the authorization server should be performed using HyperText Transfer Protocol Secure (HTTPS).

For a TLS listener, you can configure a certificate _truststore_ and point to the truststore file.

.Example environment variables for fast local JWT token validation
[source,env,subs="+quotes, attributes"]
----
export OAUTH_VALID_ISSUER_URI=https://_<auth-server-address>_ <1>
export OAUTH_JWKS_ENDPOINT_URI=https://_<auth-server-address>_/jwks <2>
export OAUTH_JWKS_REFRESH_SECONDS=300 <3>
export OAUTH_JWKS_EXPIRY_SECONDS=360 <4>
export OAUTH_USERNAME_CLAIM=preferred_username <5>
export OAUTH_SSL_TRUSTSTORE_LOCATION=_<path-to-truststore-p12>_ <6>
export OAUTH_SSL_TRUSTSTORE_PASSWORD=_<my-password>_ <7>
export OAUTH_SSL_TRUSTSTORE_TYPE=pkcs12 <8>
----
<1> A valid issuer URI. Only access tokens issued by this issuer will be accepted.
<2> The JWKS endpoint URL. For example, _\https://<auth-server-address>/auth/realms/master/protocol/openid-connect/certs_.
<3> The period between endpoint refreshes (default 300).
<4> The duration the JWKs certificates are considered valid before they expire. Default is `360` seconds. If you specify a longer time, consider the risk of allowing access to revoked certificates.
<5> The user name profile claim (or key) that contains the actual user name in the token.
The user name is the _principal_ used to identify the user.
The value will depend on the authentication flow and the authorization server used.
<6> The location of the truststore used in the TLS configuration.
<7> Password to access the truststore.
<8> The truststore type in PKCS #12 format.

Instead of using environment variables, you can specify the configuration for the listener in the `server.properties` file.

.Example properties file for fast local JWT token validation
[source,env,subs="+quotes, attributes"]
----
listener.name.client.oauthbearer.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
  oauth.valid.issuer.uri="https://_<auth-server-address>_" \
  oauth.jwks.endpoint.uri="https://_<auth-server-address>_/jwks" \
  oauth.username.claim="preferred_username" \
  oauth.ssl.truststore.location="_<path-to-truststore-p12>_" \
  oauth.ssl.truststore.password="_<my-password>_" \
  oauth.ssl.truststore.type="PKCS12" ;
----

== {oauth} introspection endpoint configuration

Token validation using {oauth} an introspection endpoint treats a received access token as opaque.
The Kafka broker sends an access token to the introspection endpoint, which responds with the token information necessary for validation.
Importantly, it returns up-to-date information if the specific access token is valid, and also information about when the token expires.

To configure {oauth} introspection-based validation, you specify an _introspection endpoint URI_ rather than the JWKs endpoint URI specified for fast local JWT token validation.
Depending on the authorization server, you typically have to specify a _client ID_ and _client secret_, as the introspection endpoint is usually protected.

.Example environment variables for an introspection endpoint
[source,env,subs="+quotes, attributes"]
----
export OAUTH_INTROSPECTION_ENDPOINT_URI=https://_<auth-server-address>_/introspection <1>
export OAUTH_CLIENT_ID=kafka-broker <2>
export OAUTH_CLIENT_SECRET=kafka-broker-secret <3>
export OAUTH_SSL_TRUSTSTORE_LOCATION=_<path-to-truststore-p12>_ <4>
export OAUTH_SSL_TRUSTSTORE_PASSWORD=_<my-password>_ <5>
export OAUTH_SSL_TRUSTSTORE_TYPE=pkcs12 <6>
----
<1> The {oauth} introspection endpoint URL. For example, _\https://<auth-server-address>/auth/realms/master/protocol/openid-connect/token/introspect_.
<2> Client ID of the Kafka broker.
<3> Secret for the Kafka broker.
<4> The location of the truststore used in the TLS configuration.
<5> Password to access the truststore.
<6> The truststore type in PKCS #12 format.

Instead of using environment variables, you can specify the configuration for a listener in the `server.properties` file.

.Example properties file for an introspection endpoint
[source,env,subs="+quotes, attributes"]
----
listener.name.client.oauthbearer.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
  oauth.introspection.endpoint.uri="https://_<auth-server-address>_/introspection" \
  oauth.client.id="kafka-broker" \
  oauth.client.secret="kafka-broker-secret" \
  oauth.ssl.truststore.location="PATH_TO_P12_FILE" \
  oauth.ssl.truststore.password="TRUSTSTORE_PASSWORD" \
  oauth.ssl.truststore.type="PKCS12" ;
----
