// Module included in the following module:
//
// con-oauth-config.adoc

[id='proc-oauth-broker-config-{context}']
= Configuring {oauth} support for Kafka brokers

This procedure describes how to configure Kafka brokers so that the broker listeners are enabled to use {oauth} authentication using an authorization server.

{oauth} requires configuration of TLS listeners.
Plain listeners are not recommended.

.Before you start

For more information on the configuration and authentication of Kafka broker listeners, see:

* xref:con-kafka-listener-configuration-{context}[Listeners]
* xref:assembly-kafka-encryption-and-authentication-{context}[Encryption and authentication]

For a description of the properties used in the listener configuration, see:

* xref:con-oauth-authentication-broker-{context}[{oauth} Kafka broker configuration]


.Prerequisites

* {ProductName} and Kafka are running
* An {oauth} authorization server is deployed

.Procedure

. Check you have the following JAR files in your Kafka `libs` directory.
+
[source,xml,subs="+attributes"]
----
strimzi-kafka-oauth-common-*.jar
strimzi-kafka-oauth-server-*.jar
strimzi-kafka-oauth-client-*.jar
keycloak-common-*.jar
keycloak-core-*.jar
bcprov-*.jar
----
+
If they are not already present, the files are available from the xref:proc-downloading-amq-streams-{context}[installation archive].

. Configure the Kafka broker listener configuration in the `server.properties` file.
+
For example:
+
[source,env,subs="+attributes,quotes"]
----
sasl.enabled.mechanisms=OAUTHBEARER
listeners=CLIENT://0.0.0.0:9092
listener.security.protocol.map=CLIENT:SASL_PLAINTEXT
listener.name.client.sasl.enabled.mechanisms=OAUTHBEARER
sasl.mechanism.inter.broker.protocol=OAUTHBEARER
inter.broker.listener.name=CLIENT
listener.name.client.oauthbearer.sasl.server.callback.handler.class=io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
listener.name.client.oauthbearer.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
listener.name.clients.oauthbearer.sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
----

. Add listener environment variables to configure broker connection options.
+
The examples here show additional configuration options.
+
--
.Example 1: Local token validation using a JWKS endpoint configuration
[source,env,subs="+attributes,quotes"]
----
export OAUTH_VALID_ISSUER_URI=https://_<auth-server-address>_
export OAUTH_JWKS_ENDPOINT_URI=https://_<auth-server-address>_/jwks
export OAUTH_JWKS_REFRESH_SECONDS=300
export OAUTH_JWKS_EXPIRY_SECONDS=360
export OAUTH_USERNAME_CLAIM=preferred_username
export OAUTH_SSL_TRUSTSTORE_LOCATION=_<path-to-truststore-p12>_
export OAUTH_SSL_TRUSTSTORE_PASSWORD=_<my-password>_
export OAUTH_SSL_TRUSTSTORE_TYPE=pkcs12
----

.Example 2: Delegating token validation to the authorization server through the {oauth} introspection endpoint
[source,env,subs="+attributes,quotes"]
----
export OAUTH_INTROSPECTION_ENDPOINT_URI=https://_<auth-server-address>_/introspection
----
--

. If required, configure access to the authorization server.
+
This step is normally required for a production environment, unless a technology like _service mesh_ is used to configure secure channels outside containers.

.. Provide a custom truststore for connecting to a secured authorization server.
SSL is always required for access to the authorization server.
+
Set environment variables to configure the truststore.
+
For example:
+
[source,env,subs="+attributes,quotes"]
----
export OAUTH_CLIENT_ID=kafka-broker
export OAUTH_CLIENT_SECRET=kafka-broker-secret
export OAUTH_SSL_TRUSTSTORE_LOCATION=_<path-to-truststore-p12>_
export OAUTH_SSL_TRUSTSTORE_PASSWORD=_<my-password>_
export OAUTH_SSL_TRUSTSTORE_TYPE=pkcs12
----

.. If the certificate hostname does not match the access URL hostname, you can turn off certificate hostname validation:
+
[source,env,subs="+attributes"]
----
export OAUTH_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM= ""
----
+
The check ensures that client connection to the authorization server is authentic.
You may wish to turn off the validation in a non-production environment.

. Configure the following environment variables according to your chosen authentication flow.
+
[source,env,subs="+attributes,quotes"]
----
export OAUTH_TOKEN_ENDPOINT_URI=https://_<auth-server-address>_/token <1>
export OAUTH_VALID_ISSUER_URI=https://_<auth-server-address>_ <2>
export OAUTH_CLIENT_ID=kafka-broker <3>
export OAUTH_CLIENT_SECRET=kafka-broker-secret <4>

export OAUTH_REFRESH_TOKEN=_<my-refresh-token-for-kafka-brokers>_ <5>
export OAUTH_ACCESS_TOKEN=_<my-access-token-for-kafka-brokers>_ <6>
----
<1> The {oauth} token endpoint URL to your authorization server. For production, always use HTTPs.
<2> A valid issuer URI. Only access tokens issued by this issuer will be accepted.
<3> The configured client ID of the Kafka broker, which is the same for all brokers. This is the xref:proc-oauth-server-config-{context}[client registered with the authorization server as `kafka-broker`].
<4> The configured secret for the Kafka broker, which is the same for all brokers.
<5> (Optional) A long-lived refresh token for Kafka brokers.
<6> (Optional) A long-lived access token for Kafka brokers.

.What to do next

* xref:proc-oauth-client-config-{context}[Configure your Kafka clients to use {oauth}]
