// Module included in the following assemblies:
//
// assembly-kafka-encryption-and-authentication.adoc

[id='con-kafka-securing-listeners-{context}']

= Listener configuration

Encryption and authentication in Kafka brokers is configured per listener.
For more information about Kafka listener configuration, see xref:con-kafka-listener-configuration-{context}[].

Each listener in the Kafka broker is configured with its own security protocol.
The configuration property `listener.security.protocol.map` defines which listener uses which security protocol. 
It maps each listener name to its security protocol. 
Supported security protocols are:

`PLAINTEXT`:: Listener without any encryption or authentication.
`SSL`:: Listener using TLS encryption and, optionally, authentication using TLS client certificates.
`SASL_PLAINTEXT`:: Listener without encryption but with SASL-based authentication.
`SASL_SSL`:: Listener with TLS-based encryption and SASL-based authentication.

Given the following `listeners` configuration:

[source]
listeners=INT1://:9092,INT2://:9093,REPLICATION://:9094

the `listener.security.protocol.map` might look like this:

[source]
listener.security.protocol.map=INT1:SASL_PLAINTEXT,INT2:SASL_SSL,REPLICATION:SSL

This would configure the listener `INT1` to use unencrypted connections with SASL authentication, the listener `INT2` to use encrypted connections with SASL authentication and the `REPLICATION` interface to use TLS encryption (possibly with TLS client authentication).
The same security protocol can be used multiple times.
The following example is also a valid configuration:

[source]
listener.security.protocol.map=INT1:SSL,INT2:SSL,REPLICATION:SSL

Such a configuration would use TLS encryption and TLS authentication for all interfaces.
The following chapters will explain in more detail how to configure TLS and SASL.