// Module included in the following assemblies:
//
// assembly-kafka-connect-distributed.adoc

[id='proc-running-kafka-connect-distributed-{context}']

= Running distributed Kafka Connect

This procedure describes how to configure and run Kafka Connect in distributed mode.

.Prerequisites

* An installed and running AMQ Streams cluster.

.Running the cluster

. Edit the `/opt/kafka/config/connect-distributed.properties` Kafka Connect configuration file on all Kafka Connect worker nodes.
+
* Set the `bootstrap.server` option to point to your Kafka brokers.
* Set the `group.id` option.
* Set the `config.storage.topic` option.
* Set the `offset.storage.topic` option.
* Set the `status.storage.topic` option.
+
For example:
+
[source,ini]
----
bootstrap.servers=kafka0.my-domain.com:9092,kafka1.my-domain.com:9092,kafka2.my-domain.com:9092
group.id=my-group-id
config.storage.topic=my-group-id-configs
offset.storage.topic=my-group-id-offsets
status.storage.topic=my-group-id-status
----

. Start the Kafka Connect workers with the `/opt/kafka/config/connect-distributed.properties` configuration file on all Kafka Connect nodes.
+
[source,shell,subs=+quotes]
----
su - kafka
/opt/kafka/bin/connect-distributed.sh /opt/kafka/config/connect-distributed.properties
----

. Verify that Kafka Connect is running.
+
[source,shell,subs=+quotes]
----
jcmd | grep ConnectDistributed
----

.Additional resources

* For more information about installing AMQ Streams, see xref:proc-installing-amq-streams-{context}[].
* For more information about configuring AMQ Streams, see xref:proc-configuring-amq-streams-{context}[].
* For a complete list of supported Kafka Connect configuration options, see xref:kafka-connect-configuration-parameters-{context}[].