// Module included in the following assemblies:
//
// assembly-upgrade.adoc

[id='proc-upgrading-zookeeper-binaries-{context}']

= Upgrading ZooKeeper

This procedure describes how to upgrade ZooKeeper on a host machine.

.Prerequisites

* You are logged in to Red Hat Enterprise Linux as the `kafka` user.

.Procedure

For each Kafka broker in your {ProductName} cluster and one at a time:

. Download the {ProductName} archive for this release from the {ReleaseDownload}.
+
NOTE: If prompted, log in to your Red Hat account.

. On the command line, create a temporary directory and extract the contents of the `amq-streams-x.y.z-bin.zip` file:
+
[source,shell,subs=+quotes]
----
mkdir /tmp/kafka
unzip amq-streams-x.y.z-bin.zip -d /tmp/kafka
----

. Delete the `libs`, `bin`, and `docs` directories from your existing installation:
+
[source,shell,subs=+quotes]
----
rm -rf /opt/kafka/libs /opt/kafka/bin /opt/kafka/docs
----

. Copy the `libs`, `bin`, and `docs` directories from the temporary directory:
+
[source,shell,subs=+quotes]
----
cp -r /tmp/kafka/kafka_y.y-x.x.x/libs /opt/kafka/
cp -r /tmp/kafka/kafka_y.y-x.x.x/bin /opt/kafka/
cp -r /tmp/kafka/kafka_y.y-x.x.x/docs /opt/kafka/
----

. Delete the temporary directory:
+
[source,shell,subs=+quotes]
----
rm -rf /tmp/kafka
----

. Restart ZooKeeper:
+
[source,shell,subs=+quotes]
----
/opt/kafka/bin/zookeeper-server-start.sh -daemon /opt/kafka/config/zookeeper.properties
----
