// This assembly is included in the following assemblies:
//
// master.adoc

[id='assembly-distributed-tracing-{context}']
= Distributed tracing

{ProductName} on {ProductPlatformName} supports distributed tracing with Jaeger for:

* Kafka Producers, Kafka Consumers, and Kafka Streams applications (referred to as _Kafka clients_)

* MirrorMaker and Kafka Connect

* Kafka Bridge

The steps to configure distributed tracing vary by client and component. However, three high-level tasks are involved:

. Enable a Jaeger tracer for the client or component.

. Enable the Interceptors for the client or component.
+
* For Kafka clients, enabling the Interceptors involves __instrumenting__ your application code for OpenTracing.
* For MirrorMaker, Kafka Connect, and the Kafka Bridge, enabling the Interceptors involves setting configuration properties for each component.

. Set tracing environment variables before deploying the client or component.

This chapter provides an overview of distributed tracing, as well as instructions for configuring supported clients and components. Setting up distributed tracing for applications and systems beyond {ProductName} is outside the scope of this chapter. To learn more about this subject, see the {OpenTracingDocs} and search for "inject and extract".

NOTE: Distributed tracing is not supported for Kafka brokers.

.Prerequisites

* The Jaeger backend components are deployed to the host operating system. For deployment instructions, see the https://www.jaegertracing.io/docs/1.14/deployment/[Jaeger deployment documentation^].

include::../modules/tracing/con-overview-distributed-tracing.adoc[leveloffset=+1]

include::assembly-setting-up-tracing-kafka-clients.adoc[leveloffset=+1]

include::assembly-configuring-mirrormaker-kafka-connect-tracing.adoc[leveloffset=+1]

include::../modules/tracing/proc-enabling-tracing-for-kafka-bridge.adoc[leveloffset=+1]

include::../modules/tracing/ref-tracing-environment-variables.adoc[leveloffset=+1]
